// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package cudagraph

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cudaGraphTraceCudaGraphEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
		Comm        [16]int8
	}
	DurationNs   uint64
	StreamHandle uint64
	GraphHandle  uint64
	ExecHandle   uint64
	CaptureMode  uint32
	ReturnCode   int32
}

type cudaGraphTraceGraphEntryState struct {
	_            structs.HostLayout
	TimestampNs  uint64
	Op           uint8
	Pad          [7]uint8
	StreamHandle uint64
	GraphHandle  uint64
	ExecHandle   uint64
	CaptureMode  uint32
	Pad2         uint32
}

type cudaGraphTraceIngeroConfig struct {
	_            structs.HostLayout
	CaptureStack uint8
	Pad1         [3]uint8
	SamplingRate uint32
	Pad2         uint32
}

// loadCudaGraphTrace returns the embedded CollectionSpec for cudaGraphTrace.
func loadCudaGraphTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CudaGraphTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cudaGraphTrace: %w", err)
	}

	return spec, err
}

// loadCudaGraphTraceObjects loads cudaGraphTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cudaGraphTraceObjects
//	*cudaGraphTracePrograms
//	*cudaGraphTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCudaGraphTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCudaGraphTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cudaGraphTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaGraphTraceSpecs struct {
	cudaGraphTraceProgramSpecs
	cudaGraphTraceMapSpecs
	cudaGraphTraceVariableSpecs
}

// cudaGraphTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaGraphTraceProgramSpecs struct {
	UprobeGraphBeginCapture    *ebpf.ProgramSpec `ebpf:"uprobe_graph_begin_capture"`
	UprobeGraphEndCapture      *ebpf.ProgramSpec `ebpf:"uprobe_graph_end_capture"`
	UprobeGraphInstantiate     *ebpf.ProgramSpec `ebpf:"uprobe_graph_instantiate"`
	UprobeGraphLaunch          *ebpf.ProgramSpec `ebpf:"uprobe_graph_launch"`
	UretprobeGraphBeginCapture *ebpf.ProgramSpec `ebpf:"uretprobe_graph_begin_capture"`
	UretprobeGraphEndCapture   *ebpf.ProgramSpec `ebpf:"uretprobe_graph_end_capture"`
	UretprobeGraphInstantiate  *ebpf.ProgramSpec `ebpf:"uretprobe_graph_instantiate"`
	UretprobeGraphLaunch       *ebpf.ProgramSpec `ebpf:"uretprobe_graph_launch"`
}

// cudaGraphTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaGraphTraceMapSpecs struct {
	GraphConfigMap     *ebpf.MapSpec `ebpf:"graph_config_map"`
	GraphEntryMap      *ebpf.MapSpec `ebpf:"graph_entry_map"`
	GraphEvents        *ebpf.MapSpec `ebpf:"graph_events"`
	GraphSampleCounter *ebpf.MapSpec `ebpf:"graph_sample_counter"`
	IngeroWatchdog     *ebpf.MapSpec `ebpf:"ingero_watchdog"`
}

// cudaGraphTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaGraphTraceVariableSpecs struct {
	UnusedCudaGraphEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_cuda_graph_event_force_btf"`
	UnusedGraphConfigForceBtf    *ebpf.VariableSpec `ebpf:"_unused_graph_config_force_btf"`
}

// cudaGraphTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCudaGraphTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaGraphTraceObjects struct {
	cudaGraphTracePrograms
	cudaGraphTraceMaps
	cudaGraphTraceVariables
}

func (o *cudaGraphTraceObjects) Close() error {
	return _CudaGraphTraceClose(
		&o.cudaGraphTracePrograms,
		&o.cudaGraphTraceMaps,
	)
}

// cudaGraphTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCudaGraphTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaGraphTraceMaps struct {
	GraphConfigMap     *ebpf.Map `ebpf:"graph_config_map"`
	GraphEntryMap      *ebpf.Map `ebpf:"graph_entry_map"`
	GraphEvents        *ebpf.Map `ebpf:"graph_events"`
	GraphSampleCounter *ebpf.Map `ebpf:"graph_sample_counter"`
	IngeroWatchdog     *ebpf.Map `ebpf:"ingero_watchdog"`
}

func (m *cudaGraphTraceMaps) Close() error {
	return _CudaGraphTraceClose(
		m.GraphConfigMap,
		m.GraphEntryMap,
		m.GraphEvents,
		m.GraphSampleCounter,
		m.IngeroWatchdog,
	)
}

// cudaGraphTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCudaGraphTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaGraphTraceVariables struct {
	UnusedCudaGraphEventForceBtf *ebpf.Variable `ebpf:"_unused_cuda_graph_event_force_btf"`
	UnusedGraphConfigForceBtf    *ebpf.Variable `ebpf:"_unused_graph_config_force_btf"`
}

// cudaGraphTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCudaGraphTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaGraphTracePrograms struct {
	UprobeGraphBeginCapture    *ebpf.Program `ebpf:"uprobe_graph_begin_capture"`
	UprobeGraphEndCapture      *ebpf.Program `ebpf:"uprobe_graph_end_capture"`
	UprobeGraphInstantiate     *ebpf.Program `ebpf:"uprobe_graph_instantiate"`
	UprobeGraphLaunch          *ebpf.Program `ebpf:"uprobe_graph_launch"`
	UretprobeGraphBeginCapture *ebpf.Program `ebpf:"uretprobe_graph_begin_capture"`
	UretprobeGraphEndCapture   *ebpf.Program `ebpf:"uretprobe_graph_end_capture"`
	UretprobeGraphInstantiate  *ebpf.Program `ebpf:"uretprobe_graph_instantiate"`
	UretprobeGraphLaunch       *ebpf.Program `ebpf:"uretprobe_graph_launch"`
}

func (p *cudaGraphTracePrograms) Close() error {
	return _CudaGraphTraceClose(
		p.UprobeGraphBeginCapture,
		p.UprobeGraphEndCapture,
		p.UprobeGraphInstantiate,
		p.UprobeGraphLaunch,
		p.UretprobeGraphBeginCapture,
		p.UretprobeGraphEndCapture,
		p.UretprobeGraphInstantiate,
		p.UretprobeGraphLaunch,
	)
}

func _CudaGraphTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cudagraphtrace_bpfel.o
var _CudaGraphTraceBytes []byte
