// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ncclprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ncclTraceIngeroConfig struct {
	_            structs.HostLayout
	CaptureStack uint8
	Pad1         [3]uint8
	SamplingRate uint32
	Pad2         uint32
}

type ncclTraceNcclCommKey struct {
	_       structs.HostLayout
	Pid     uint32
	Pad     uint32
	CommPtr uint64
}

type ncclTraceNcclCommValue struct {
	_          structs.HostLayout
	CommIdHash uint64
	Rank       uint32
	Nranks     uint32
	InitTs     uint64
}

type ncclTraceNcclEntryState struct {
	_            structs.HostLayout
	TimestampNs  uint64
	Op           uint8
	Pad          [7]uint8
	CommPtr      uint64
	CommOutPtr   uint64
	Count        uint64
	Stream       uint64
	Datatype     uint32
	ReduceOp     uint32
	NranksArg    uint32
	RankArg      uint32
	CommidFirst8 uint64
}

type ncclTraceNcclEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
		Comm        [16]int8
	}
	DurationNs   uint64
	CommIdHash   uint64
	StreamHandle uint64
	CountBytes   uint64
	Rank         uint32
	Nranks       uint32
	Datatype     uint32
	ReduceOp     uint32
	ReturnCode   int32
	Pad          uint32
}

// loadNcclTrace returns the embedded CollectionSpec for ncclTrace.
func loadNcclTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NcclTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ncclTrace: %w", err)
	}

	return spec, err
}

// loadNcclTraceObjects loads ncclTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ncclTraceObjects
//	*ncclTracePrograms
//	*ncclTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNcclTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNcclTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ncclTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ncclTraceSpecs struct {
	ncclTraceProgramSpecs
	ncclTraceMapSpecs
	ncclTraceVariableSpecs
}

// ncclTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ncclTraceProgramSpecs struct {
	UprobeNcclAllGather        *ebpf.ProgramSpec `ebpf:"uprobe_nccl_all_gather"`
	UprobeNcclAllReduce        *ebpf.ProgramSpec `ebpf:"uprobe_nccl_all_reduce"`
	UprobeNcclBcast            *ebpf.ProgramSpec `ebpf:"uprobe_nccl_bcast"`
	UprobeNcclCommDestroy      *ebpf.ProgramSpec `ebpf:"uprobe_nccl_comm_destroy"`
	UprobeNcclCommInitRank     *ebpf.ProgramSpec `ebpf:"uprobe_nccl_comm_init_rank"`
	UprobeNcclReduceScatter    *ebpf.ProgramSpec `ebpf:"uprobe_nccl_reduce_scatter"`
	UretprobeNcclAllGather     *ebpf.ProgramSpec `ebpf:"uretprobe_nccl_all_gather"`
	UretprobeNcclAllReduce     *ebpf.ProgramSpec `ebpf:"uretprobe_nccl_all_reduce"`
	UretprobeNcclBcast         *ebpf.ProgramSpec `ebpf:"uretprobe_nccl_bcast"`
	UretprobeNcclCommDestroy   *ebpf.ProgramSpec `ebpf:"uretprobe_nccl_comm_destroy"`
	UretprobeNcclCommInitRank  *ebpf.ProgramSpec `ebpf:"uretprobe_nccl_comm_init_rank"`
	UretprobeNcclReduceScatter *ebpf.ProgramSpec `ebpf:"uretprobe_nccl_reduce_scatter"`
}

// ncclTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ncclTraceMapSpecs struct {
	ConfigMap      *ebpf.MapSpec `ebpf:"config_map"`
	IngeroWatchdog *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	NcclCommMap    *ebpf.MapSpec `ebpf:"nccl_comm_map"`
	NcclEntryMap   *ebpf.MapSpec `ebpf:"nccl_entry_map"`
	NcclEvents     *ebpf.MapSpec `ebpf:"nccl_events"`
}

// ncclTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ncclTraceVariableSpecs struct {
	UnusedIngeroConfigForceBtfNccl *ebpf.VariableSpec `ebpf:"_unused_ingero_config_force_btf_nccl"`
	UnusedNcclCommKeyForceBtf      *ebpf.VariableSpec `ebpf:"_unused_nccl_comm_key_force_btf"`
	UnusedNcclCommValueForceBtf    *ebpf.VariableSpec `ebpf:"_unused_nccl_comm_value_force_btf"`
	UnusedNcclEntryStateForceBtf   *ebpf.VariableSpec `ebpf:"_unused_nccl_entry_state_force_btf"`
	UnusedNcclEventForceBtf        *ebpf.VariableSpec `ebpf:"_unused_nccl_event_force_btf"`
}

// ncclTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNcclTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ncclTraceObjects struct {
	ncclTracePrograms
	ncclTraceMaps
	ncclTraceVariables
}

func (o *ncclTraceObjects) Close() error {
	return _NcclTraceClose(
		&o.ncclTracePrograms,
		&o.ncclTraceMaps,
	)
}

// ncclTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNcclTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ncclTraceMaps struct {
	ConfigMap      *ebpf.Map `ebpf:"config_map"`
	IngeroWatchdog *ebpf.Map `ebpf:"ingero_watchdog"`
	NcclCommMap    *ebpf.Map `ebpf:"nccl_comm_map"`
	NcclEntryMap   *ebpf.Map `ebpf:"nccl_entry_map"`
	NcclEvents     *ebpf.Map `ebpf:"nccl_events"`
}

func (m *ncclTraceMaps) Close() error {
	return _NcclTraceClose(
		m.ConfigMap,
		m.IngeroWatchdog,
		m.NcclCommMap,
		m.NcclEntryMap,
		m.NcclEvents,
	)
}

// ncclTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNcclTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ncclTraceVariables struct {
	UnusedIngeroConfigForceBtfNccl *ebpf.Variable `ebpf:"_unused_ingero_config_force_btf_nccl"`
	UnusedNcclCommKeyForceBtf      *ebpf.Variable `ebpf:"_unused_nccl_comm_key_force_btf"`
	UnusedNcclCommValueForceBtf    *ebpf.Variable `ebpf:"_unused_nccl_comm_value_force_btf"`
	UnusedNcclEntryStateForceBtf   *ebpf.Variable `ebpf:"_unused_nccl_entry_state_force_btf"`
	UnusedNcclEventForceBtf        *ebpf.Variable `ebpf:"_unused_nccl_event_force_btf"`
}

// ncclTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNcclTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ncclTracePrograms struct {
	UprobeNcclAllGather        *ebpf.Program `ebpf:"uprobe_nccl_all_gather"`
	UprobeNcclAllReduce        *ebpf.Program `ebpf:"uprobe_nccl_all_reduce"`
	UprobeNcclBcast            *ebpf.Program `ebpf:"uprobe_nccl_bcast"`
	UprobeNcclCommDestroy      *ebpf.Program `ebpf:"uprobe_nccl_comm_destroy"`
	UprobeNcclCommInitRank     *ebpf.Program `ebpf:"uprobe_nccl_comm_init_rank"`
	UprobeNcclReduceScatter    *ebpf.Program `ebpf:"uprobe_nccl_reduce_scatter"`
	UretprobeNcclAllGather     *ebpf.Program `ebpf:"uretprobe_nccl_all_gather"`
	UretprobeNcclAllReduce     *ebpf.Program `ebpf:"uretprobe_nccl_all_reduce"`
	UretprobeNcclBcast         *ebpf.Program `ebpf:"uretprobe_nccl_bcast"`
	UretprobeNcclCommDestroy   *ebpf.Program `ebpf:"uretprobe_nccl_comm_destroy"`
	UretprobeNcclCommInitRank  *ebpf.Program `ebpf:"uretprobe_nccl_comm_init_rank"`
	UretprobeNcclReduceScatter *ebpf.Program `ebpf:"uretprobe_nccl_reduce_scatter"`
}

func (p *ncclTracePrograms) Close() error {
	return _NcclTraceClose(
		p.UprobeNcclAllGather,
		p.UprobeNcclAllReduce,
		p.UprobeNcclBcast,
		p.UprobeNcclCommDestroy,
		p.UprobeNcclCommInitRank,
		p.UprobeNcclReduceScatter,
		p.UretprobeNcclAllGather,
		p.UretprobeNcclAllReduce,
		p.UretprobeNcclBcast,
		p.UretprobeNcclCommDestroy,
		p.UretprobeNcclCommInitRank,
		p.UretprobeNcclReduceScatter,
	)
}

func _NcclTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nccltrace_x86_bpfel.o
var _NcclTraceBytes []byte
