// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package tcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpTraceIngeroTcpEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
	}
	Saddr  uint32
	Daddr  uint32
	Sport  uint16
	Dport  uint16
	State  uint8
	PadTcp [3]uint8
}

// loadTcpTrace returns the embedded CollectionSpec for tcpTrace.
func loadTcpTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpTrace: %w", err)
	}

	return spec, err
}

// loadTcpTraceObjects loads tcpTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpTraceObjects
//	*tcpTracePrograms
//	*tcpTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTraceSpecs struct {
	tcpTraceProgramSpecs
	tcpTraceMapSpecs
	tcpTraceVariableSpecs
}

// tcpTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTraceProgramSpecs struct {
	HandleTcpRetransmit *ebpf.ProgramSpec `ebpf:"handle_tcp_retransmit"`
}

// tcpTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTraceMapSpecs struct {
	IngeroWatchdog *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	TcpEvents      *ebpf.MapSpec `ebpf:"tcp_events"`
}

// tcpTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTraceVariableSpecs struct {
	UnusedTcpEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_tcp_event_force_btf"`
}

// tcpTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTraceObjects struct {
	tcpTracePrograms
	tcpTraceMaps
	tcpTraceVariables
}

func (o *tcpTraceObjects) Close() error {
	return _TcpTraceClose(
		&o.tcpTracePrograms,
		&o.tcpTraceMaps,
	)
}

// tcpTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTraceMaps struct {
	IngeroWatchdog *ebpf.Map `ebpf:"ingero_watchdog"`
	TcpEvents      *ebpf.Map `ebpf:"tcp_events"`
}

func (m *tcpTraceMaps) Close() error {
	return _TcpTraceClose(
		m.IngeroWatchdog,
		m.TcpEvents,
	)
}

// tcpTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTraceVariables struct {
	UnusedTcpEventForceBtf *ebpf.Variable `ebpf:"_unused_tcp_event_force_btf"`
}

// tcpTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTracePrograms struct {
	HandleTcpRetransmit *ebpf.Program `ebpf:"handle_tcp_retransmit"`
}

func (p *tcpTracePrograms) Close() error {
	return _TcpTraceClose(
		p.HandleTcpRetransmit,
	)
}

func _TcpTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcptrace_bpfel.o
var _TcpTraceBytes []byte
