// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package driver

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type driverTraceCudaEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
		Comm        [16]int8
	}
	DurationNs uint64
	Arg0       uint64
	Arg1       uint64
	ReturnCode int32
	GpuId      uint32
}

type driverTraceEntryState struct {
	_           structs.HostLayout
	TimestampNs uint64
	Op          uint8
	Pad         [7]uint8
	Arg0        uint64
	Arg1        uint64
}

type driverTraceIngeroConfig struct {
	_            structs.HostLayout
	CaptureStack uint8
	Pad          [7]uint8
}

// loadDriverTrace returns the embedded CollectionSpec for driverTrace.
func loadDriverTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DriverTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load driverTrace: %w", err)
	}

	return spec, err
}

// loadDriverTraceObjects loads driverTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*driverTraceObjects
//	*driverTracePrograms
//	*driverTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDriverTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDriverTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// driverTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type driverTraceSpecs struct {
	driverTraceProgramSpecs
	driverTraceMapSpecs
	driverTraceVariableSpecs
}

// driverTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type driverTraceProgramSpecs struct {
	UprobeCuCtxSync            *ebpf.ProgramSpec `ebpf:"uprobe_cu_ctx_sync"`
	UprobeCuLaunchKernel       *ebpf.ProgramSpec `ebpf:"uprobe_cu_launch_kernel"`
	UprobeCuMemAlloc           *ebpf.ProgramSpec `ebpf:"uprobe_cu_mem_alloc"`
	UprobeCuMemAllocManaged    *ebpf.ProgramSpec `ebpf:"uprobe_cu_mem_alloc_managed"`
	UprobeCuMemcpy             *ebpf.ProgramSpec `ebpf:"uprobe_cu_memcpy"`
	UprobeCuMemcpyAsync        *ebpf.ProgramSpec `ebpf:"uprobe_cu_memcpy_async"`
	UretprobeCuCtxSync         *ebpf.ProgramSpec `ebpf:"uretprobe_cu_ctx_sync"`
	UretprobeCuLaunchKernel    *ebpf.ProgramSpec `ebpf:"uretprobe_cu_launch_kernel"`
	UretprobeCuMemAlloc        *ebpf.ProgramSpec `ebpf:"uretprobe_cu_mem_alloc"`
	UretprobeCuMemAllocManaged *ebpf.ProgramSpec `ebpf:"uretprobe_cu_mem_alloc_managed"`
	UretprobeCuMemcpy          *ebpf.ProgramSpec `ebpf:"uretprobe_cu_memcpy"`
	UretprobeCuMemcpyAsync     *ebpf.ProgramSpec `ebpf:"uretprobe_cu_memcpy_async"`
}

// driverTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type driverTraceMapSpecs struct {
	DriverConfigMap *ebpf.MapSpec `ebpf:"driver_config_map"`
	DriverEntryMap  *ebpf.MapSpec `ebpf:"driver_entry_map"`
	DriverEvents    *ebpf.MapSpec `ebpf:"driver_events"`
	IngeroWatchdog  *ebpf.MapSpec `ebpf:"ingero_watchdog"`
}

// driverTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type driverTraceVariableSpecs struct {
	UnusedDriverConfigForceBtf     *ebpf.VariableSpec `ebpf:"_unused_driver_config_force_btf"`
	UnusedDriverEventForceBtf      *ebpf.VariableSpec `ebpf:"_unused_driver_event_force_btf"`
	UnusedDriverEventStackForceBtf *ebpf.VariableSpec `ebpf:"_unused_driver_event_stack_force_btf"`
}

// driverTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDriverTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type driverTraceObjects struct {
	driverTracePrograms
	driverTraceMaps
	driverTraceVariables
}

func (o *driverTraceObjects) Close() error {
	return _DriverTraceClose(
		&o.driverTracePrograms,
		&o.driverTraceMaps,
	)
}

// driverTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDriverTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type driverTraceMaps struct {
	DriverConfigMap *ebpf.Map `ebpf:"driver_config_map"`
	DriverEntryMap  *ebpf.Map `ebpf:"driver_entry_map"`
	DriverEvents    *ebpf.Map `ebpf:"driver_events"`
	IngeroWatchdog  *ebpf.Map `ebpf:"ingero_watchdog"`
}

func (m *driverTraceMaps) Close() error {
	return _DriverTraceClose(
		m.DriverConfigMap,
		m.DriverEntryMap,
		m.DriverEvents,
		m.IngeroWatchdog,
	)
}

// driverTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDriverTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type driverTraceVariables struct {
	UnusedDriverConfigForceBtf     *ebpf.Variable `ebpf:"_unused_driver_config_force_btf"`
	UnusedDriverEventForceBtf      *ebpf.Variable `ebpf:"_unused_driver_event_force_btf"`
	UnusedDriverEventStackForceBtf *ebpf.Variable `ebpf:"_unused_driver_event_stack_force_btf"`
}

// driverTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDriverTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type driverTracePrograms struct {
	UprobeCuCtxSync            *ebpf.Program `ebpf:"uprobe_cu_ctx_sync"`
	UprobeCuLaunchKernel       *ebpf.Program `ebpf:"uprobe_cu_launch_kernel"`
	UprobeCuMemAlloc           *ebpf.Program `ebpf:"uprobe_cu_mem_alloc"`
	UprobeCuMemAllocManaged    *ebpf.Program `ebpf:"uprobe_cu_mem_alloc_managed"`
	UprobeCuMemcpy             *ebpf.Program `ebpf:"uprobe_cu_memcpy"`
	UprobeCuMemcpyAsync        *ebpf.Program `ebpf:"uprobe_cu_memcpy_async"`
	UretprobeCuCtxSync         *ebpf.Program `ebpf:"uretprobe_cu_ctx_sync"`
	UretprobeCuLaunchKernel    *ebpf.Program `ebpf:"uretprobe_cu_launch_kernel"`
	UretprobeCuMemAlloc        *ebpf.Program `ebpf:"uretprobe_cu_mem_alloc"`
	UretprobeCuMemAllocManaged *ebpf.Program `ebpf:"uretprobe_cu_mem_alloc_managed"`
	UretprobeCuMemcpy          *ebpf.Program `ebpf:"uretprobe_cu_memcpy"`
	UretprobeCuMemcpyAsync     *ebpf.Program `ebpf:"uretprobe_cu_memcpy_async"`
}

func (p *driverTracePrograms) Close() error {
	return _DriverTraceClose(
		p.UprobeCuCtxSync,
		p.UprobeCuLaunchKernel,
		p.UprobeCuMemAlloc,
		p.UprobeCuMemAllocManaged,
		p.UprobeCuMemcpy,
		p.UprobeCuMemcpyAsync,
		p.UretprobeCuCtxSync,
		p.UretprobeCuLaunchKernel,
		p.UretprobeCuMemAlloc,
		p.UretprobeCuMemAllocManaged,
		p.UretprobeCuMemcpy,
		p.UretprobeCuMemcpyAsync,
	)
}

func _DriverTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed drivertrace_bpfel.o
var _DriverTraceBytes []byte
