// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package host

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type hostTraceHostEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		_           [4]byte
	}
	DurationNs uint64
	Cpu        uint32
	TargetPid  uint32
}

// loadHostTrace returns the embedded CollectionSpec for hostTrace.
func loadHostTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HostTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hostTrace: %w", err)
	}

	return spec, err
}

// loadHostTraceObjects loads hostTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hostTraceObjects
//	*hostTracePrograms
//	*hostTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHostTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHostTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hostTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostTraceSpecs struct {
	hostTraceProgramSpecs
	hostTraceMapSpecs
	hostTraceVariableSpecs
}

// hostTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostTraceProgramSpecs struct {
	HandleMmPageAlloc *ebpf.ProgramSpec `ebpf:"handle_mm_page_alloc"`
	HandleOomKill     *ebpf.ProgramSpec `ebpf:"handle_oom_kill"`
	HandleProcessExec *ebpf.ProgramSpec `ebpf:"handle_process_exec"`
	HandleProcessExit *ebpf.ProgramSpec `ebpf:"handle_process_exit"`
	HandleProcessFork *ebpf.ProgramSpec `ebpf:"handle_process_fork"`
	HandleSchedSwitch *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSchedWakeup *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
}

// hostTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostTraceMapSpecs struct {
	HostEvents  *ebpf.MapSpec `ebpf:"host_events"`
	SchedOffMap *ebpf.MapSpec `ebpf:"sched_off_map"`
	TargetPids  *ebpf.MapSpec `ebpf:"target_pids"`
}

// hostTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostTraceVariableSpecs struct {
	UnusedHostEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_host_event_force_btf"`
}

// hostTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHostTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostTraceObjects struct {
	hostTracePrograms
	hostTraceMaps
	hostTraceVariables
}

func (o *hostTraceObjects) Close() error {
	return _HostTraceClose(
		&o.hostTracePrograms,
		&o.hostTraceMaps,
	)
}

// hostTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHostTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostTraceMaps struct {
	HostEvents  *ebpf.Map `ebpf:"host_events"`
	SchedOffMap *ebpf.Map `ebpf:"sched_off_map"`
	TargetPids  *ebpf.Map `ebpf:"target_pids"`
}

func (m *hostTraceMaps) Close() error {
	return _HostTraceClose(
		m.HostEvents,
		m.SchedOffMap,
		m.TargetPids,
	)
}

// hostTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHostTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostTraceVariables struct {
	UnusedHostEventForceBtf *ebpf.Variable `ebpf:"_unused_host_event_force_btf"`
}

// hostTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHostTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostTracePrograms struct {
	HandleMmPageAlloc *ebpf.Program `ebpf:"handle_mm_page_alloc"`
	HandleOomKill     *ebpf.Program `ebpf:"handle_oom_kill"`
	HandleProcessExec *ebpf.Program `ebpf:"handle_process_exec"`
	HandleProcessExit *ebpf.Program `ebpf:"handle_process_exit"`
	HandleProcessFork *ebpf.Program `ebpf:"handle_process_fork"`
	HandleSchedSwitch *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSchedWakeup *ebpf.Program `ebpf:"handle_sched_wakeup"`
}

func (p *hostTracePrograms) Close() error {
	return _HostTraceClose(
		p.HandleMmPageAlloc,
		p.HandleOomKill,
		p.HandleProcessExec,
		p.HandleProcessExit,
		p.HandleProcessFork,
		p.HandleSchedSwitch,
		p.HandleSchedWakeup,
	)
}

func _HostTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hosttrace_bpfel.o
var _HostTraceBytes []byte
