package host

import (
	"context"
	"errors"
	"fmt"
	"sync/atomic"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/ingero-io/ingero/pkg/events"
)

// Tracer attaches eBPF tracepoints to kernel scheduler and memory subsystem
// events and streams them to a Go channel. Host events are correlated with
// CUDA events to explain latency spikes.
//
// Usage:
//
//	t := host.New(targetPID)
//	if err := t.Attach(); err != nil { ... }
//	defer t.Close()
//	go t.Run(ctx)
//	for evt := range t.Events() { ... }
type Tracer struct {
	targetPID   uint32                // primary PID to filter (tgid)
	ringBufSize uint32                // 0 = use compiled default
	objs        hostTraceObjects      // generated by bpf2go: maps + programs
	links       []link.Link           // attached tracepoints (must Close on shutdown)
	reader      *ringbuf.Reader       // reads events from kernel ring buffer
	eventCh     chan events.Event     // output channel for parsed events
	dropped     atomic.Uint64         // events dropped due to full channel
	readErrors  atomic.Uint64         // ring buffer read errors
	parseErrors atomic.Uint64         // event parse failures
	closed      atomic.Bool           // prevents double-close
}

// Option configures a Tracer.
type Option func(*Tracer)

// WithRingBufSize overrides the compiled-in ring buffer size (default 1MB).
// The value must be a power of 2 and at least 4096 (one page).
func WithRingBufSize(bytes uint32) Option {
	return func(t *Tracer) {
		t.ringBufSize = bytes
	}
}

// New creates a new host kernel tracer that filters events for targetPID.
// Call Attach() to start tracing, then read events from Events() channel.
func New(targetPID uint32, opts ...Option) *Tracer {
	t := &Tracer{
		targetPID: targetPID,
		eventCh:   make(chan events.Event, 4096),
	}
	for _, opt := range opts {
		opt(t)
	}
	return t
}

// Attach loads the eBPF program, populates the target_pids map, and
// attaches tracepoints to sched_switch, sched_wakeup, mm_page_alloc,
// and oom/mark_victim.
func (t *Tracer) Attach() error {
	spec, err := loadHostTrace()
	if err != nil {
		return fmt.Errorf("loading host eBPF spec: %w", err)
	}

	if t.ringBufSize > 0 {
		if eventsMap, ok := spec.Maps["host_events"]; ok {
			eventsMap.MaxEntries = t.ringBufSize
		}
	}

	if err := spec.LoadAndAssign(&t.objs, nil); err != nil {
		return fmt.Errorf("loading host eBPF objects: %w", err)
	}

	var closeFn func()
	closeFn = func() {
		for _, l := range t.links {
			l.Close()
		}
		t.links = nil
		t.objs.Close()
	}
	defer func() {
		if closeFn != nil {
			closeFn()
		}
	}()

	// Populate the target_pids map with the initial PID (if known).
	// When targetPID is 0 (watching all processes), PIDs are added
	// dynamically via SetTargetPID() as CUDA events arrive.
	if t.targetPID > 0 {
		var val uint8 = 1
		if err := t.objs.TargetPids.Put(t.targetPID, val); err != nil {
			return fmt.Errorf("setting target PID %d: %w", t.targetPID, err)
		}
	}

	// Attach tracepoints.
	type tpSpec struct {
		group   string
		name    string
		prog    *ebpf.Program
	}

	// Core tracepoints — required for host correlation.
	coreSpecs := []tpSpec{
		{"sched", "sched_switch", t.objs.HandleSchedSwitch},
		{"sched", "sched_wakeup", t.objs.HandleSchedWakeup},
		{"kmem", "mm_page_alloc", t.objs.HandleMmPageAlloc},
		{"oom", "mark_victim", t.objs.HandleOomKill},
	}

	for _, spec := range coreSpecs {
		tp, err := link.Tracepoint(spec.group, spec.name, spec.prog, nil)
		if err != nil {
			return fmt.Errorf("attaching tracepoint %s/%s: %w", spec.group, spec.name, err)
		}
		t.links = append(t.links, tp)
	}

	// Process lifecycle tracepoints — optional, non-fatal on older kernels.
	optionalSpecs := []tpSpec{
		{"sched", "sched_process_exec", t.objs.HandleProcessExec},
		{"sched", "sched_process_exit", t.objs.HandleProcessExit},
		{"sched", "sched_process_fork", t.objs.HandleProcessFork},
	}

	for _, spec := range optionalSpecs {
		tp, err := link.Tracepoint(spec.group, spec.name, spec.prog, nil)
		if err != nil {
			// Non-fatal: process lifecycle tracing is optional.
			continue
		}
		t.links = append(t.links, tp)
	}

	// Create ring buffer reader for host_events map.
	t.reader, err = ringbuf.NewReader(t.objs.HostEvents)
	if err != nil {
		return fmt.Errorf("creating host ring buffer reader: %w", err)
	}

	closeFn = nil
	return nil
}

// SetTargetPID adds or updates a PID in the in-kernel filter map.
// This allows dynamic PID tracking without reloading the eBPF program.
func (t *Tracer) SetTargetPID(pid uint32) error {
	var val uint8 = 1
	if err := t.objs.TargetPids.Put(pid, val); err != nil {
		return fmt.Errorf("setting target PID %d: %w", pid, err)
	}
	return nil
}

// RemoveTargetPID removes a PID from the in-kernel filter map.
func (t *Tracer) RemoveTargetPID(pid uint32) error {
	if err := t.objs.TargetPids.Delete(pid); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
		return fmt.Errorf("removing target PID %d: %w", pid, err)
	}
	return nil
}

// SetTargetCGroup adds a cgroup ID to the in-kernel cgroup filter map.
// Parallel to SetTargetPID — allows K8s container scoping by cgroup v2 ID
// without fragile PID enumeration. The eBPF program checks both maps.
func (t *Tracer) SetTargetCGroup(cgroupID uint64) error {
	var val uint8 = 1
	if err := t.objs.TargetCgroups.Put(cgroupID, val); err != nil {
		return fmt.Errorf("setting target cgroup %d: %w", cgroupID, err)
	}
	return nil
}

// RemoveTargetCGroup removes a cgroup ID from the in-kernel filter map.
func (t *Tracer) RemoveTargetCGroup(cgroupID uint64) error {
	if err := t.objs.TargetCgroups.Delete(cgroupID); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
		return fmt.Errorf("removing target cgroup %d: %w", cgroupID, err)
	}
	return nil
}

// Events returns the channel on which parsed host events are delivered.
func (t *Tracer) Events() <-chan events.Event {
	return t.eventCh
}

// Run starts reading events from the eBPF ring buffer and sending them
// to the Events() channel. Blocks until ctx is cancelled.
func (t *Tracer) Run(ctx context.Context) {
	defer close(t.eventCh)

	go func() {
		<-ctx.Done()
		t.reader.Close()
	}()

	for {
		record, err := t.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			t.readErrors.Add(1)
			continue
		}

		evt, err := parseEvent(record.RawSample)
		if err != nil {
			t.parseErrors.Add(1)
			continue
		}

		select {
		case t.eventCh <- evt:
		default:
			t.dropped.Add(1)
		}
	}
}

// parseEvent converts raw bytes from the ring buffer into a typed Event.
// The ring buffer delivers bytes matching the C struct host_event layout.
func parseEvent(raw []byte) (events.Event, error) {
	eventSize := int(unsafe.Sizeof(hostTraceHostEvent{}))
	if len(raw) < eventSize {
		return events.Event{}, fmt.Errorf("host event too short: %d bytes, need %d", len(raw), eventSize)
	}

	he := (*hostTraceHostEvent)(unsafe.Pointer(&raw[0]))

	// For mm_page_alloc, duration_ns carries the allocation size in bytes.
	// We store it in Args[0] and set Duration to 0.
	var dur time.Duration
	var args [2]uint64
	if he.Hdr.Op == uint8(events.HostPageAlloc) {
		args[0] = he.DurationNs // alloc_bytes
		dur = 0
	} else {
		dur = time.Duration(he.DurationNs)
	}

	// target_pid goes in Args[1] for sched events.
	// For sched_switch: this is prev_pid (the process that was running
	// before the target resumed — the most recent preemptor).
	args[1] = uint64(he.TargetPid)

	return events.Event{
		Timestamp: events.KtimeToWallClock(he.Hdr.TimestampNs),
		PID:       he.Hdr.Pid,
		TID:       he.Hdr.Tid,
		Comm:      events.CommToString(he.Hdr.Comm),
		Source:    events.Source(he.Hdr.Source),
		Op:        he.Hdr.Op,
		Duration:  dur,
		GPUID:     0,
		Args:      args,
		RetCode:   0,
		CGroupID:  he.Hdr.CgroupId,
	}, nil
}

// Close releases all eBPF resources. Safe to call multiple times (idempotent).
func (t *Tracer) Close() error {
	if t.closed.Swap(true) {
		return nil
	}

	var errs []error
	if t.reader != nil {
		if err := t.reader.Close(); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errs = append(errs, err)
		}
	}
	for _, l := range t.links {
		if err := l.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	t.links = nil
	if err := t.objs.Close(); err != nil {
		errs = append(errs, fmt.Errorf("closing host eBPF objects: %w", err))
	}
	return errors.Join(errs...)
}

// Dropped returns the number of events dropped due to a full channel.
func (t *Tracer) Dropped() uint64 {
	return t.dropped.Load()
}

// ReadErrors returns the number of ring buffer read errors.
func (t *Tracer) ReadErrors() uint64 {
	return t.readErrors.Load()
}

// ParseErrors returns the number of malformed events that failed to parse.
func (t *Tracer) ParseErrors() uint64 {
	return t.parseErrors.Load()
}
