package host

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"reflect"
	"runtime"
	"sync/atomic"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/ingero-io/ingero/pkg/events"
)

// reflectMapField looks up a named field on a hostTraceObjects value and
// returns it as *ebpf.Map. Returns nil if the field does not exist (the
// bpf2go bindings haven't been regenerated after adding a new map in the
// C source) or if the field is nil (objects not yet loaded).
//
// This indirection keeps the code compiling on Windows where `make
// generate` cannot be run. Once the bindings catch up, this can be
// replaced with direct field access: `t.objs.MmAllocAgg`.
func reflectMapField(objs *hostTraceObjects, fieldName string) *ebpf.Map {
	if objs == nil {
		return nil
	}
	v := reflect.ValueOf(objs).Elem()
	// Fields live on the embedded hostTraceMaps struct.
	mapsField := v.FieldByName("hostTraceMaps")
	if !mapsField.IsValid() {
		return nil
	}
	f := mapsField.FieldByName(fieldName)
	if !f.IsValid() || f.IsNil() {
		return nil
	}
	m, ok := f.Interface().(*ebpf.Map)
	if !ok {
		return nil
	}
	return m
}

// Aggregation map key/value layouts must mirror the C structs in
// bpf/host_trace.bpf.c exactly. bpf2go regenerates typed bindings on Linux,
// but we define these explicitly so the drain code is readable regardless
// of which bpf2go version is in use.

// mmAllocStats mirrors `struct mm_alloc_stats` in host_trace.bpf.c.
type mmAllocStats struct {
	Count      uint64
	TotalBytes uint64
	LastTs     uint64
}

// schedSwitchStats mirrors `struct sched_switch_stats` in host_trace.bpf.c.
type schedSwitchStats struct {
	Count         uint64
	TotalOffCPUNs uint64
	LastTs        uint64
}

// drainTickInterval is the period at which aggregation maps are drained
// and summary events emitted to the event channel.
const drainTickInterval = 1 * time.Second

// Tracer attaches eBPF tracepoints to kernel scheduler and memory subsystem
// events and streams them to a Go channel. Host events are correlated with
// CUDA events to explain latency spikes.
//
// Usage:
//
//	t := host.New(targetPID)
//	if err := t.Attach(); err != nil { ... }
//	defer t.Close()
//	go t.Run(ctx)
//	for evt := range t.Events() { ... }
type Tracer struct {
	targetPID       uint32                // primary PID to filter (tgid)
	ringBufSize     uint32                // 0 = use compiled default
	objs            hostTraceObjects      // generated by bpf2go: maps + programs
	links           []link.Link           // attached tracepoints (must Close on shutdown)
	reader          *ringbuf.Reader       // reads events from kernel ring buffer
	criticalReader  *ringbuf.Reader       // reader for critical_events buffer
	eventCh         chan events.Event     // output channel for parsed events
	dropped         atomic.Uint64         // events dropped due to full channel
	criticalDropped atomic.Uint64         // always 0 — runCriticalReader blocks instead of dropping
	readErrors      atomic.Uint64         // ring buffer read errors
	parseErrors     atomic.Uint64         // event parse failures
	closed          atomic.Bool           // prevents double-close
}

// Option configures a Tracer.
type Option func(*Tracer)

// WithRingBufSize overrides the compiled-in ring buffer size (default 1MB).
// The value must be a power of 2 and at least 4096 (one page).
func WithRingBufSize(bytes uint32) Option {
	return func(t *Tracer) {
		t.ringBufSize = bytes
	}
}

// New creates a new host kernel tracer that filters events for targetPID.
// Call Attach() to start tracing, then read events from Events() channel.
func New(targetPID uint32, opts ...Option) *Tracer {
	t := &Tracer{
		targetPID: targetPID,
		eventCh:   make(chan events.Event, 4096),
	}
	for _, opt := range opts {
		opt(t)
	}
	return t
}

// Attach loads the eBPF program, populates the target_pids map, and
// attaches tracepoints to sched_switch, sched_wakeup, mm_page_alloc,
// and oom/mark_victim.
func (t *Tracer) Attach() error {
	spec, err := loadHostTrace()
	if err != nil {
		return fmt.Errorf("loading host eBPF spec: %w", err)
	}

	if t.ringBufSize > 0 {
		if eventsMap, ok := spec.Maps["host_events"]; ok {
			eventsMap.MaxEntries = t.ringBufSize
		}
	}

	if err := spec.LoadAndAssign(&t.objs, nil); err != nil {
		return fmt.Errorf("loading host eBPF objects: %w", err)
	}

	var closeFn func()
	closeFn = func() {
		for _, l := range t.links {
			l.Close()
		}
		t.links = nil
		t.objs.Close()
	}
	defer func() {
		if closeFn != nil {
			closeFn()
		}
	}()

	// Populate the target_pids map with the initial PID (if known).
	// When targetPID is 0 (watching all processes), PIDs are added
	// dynamically via SetTargetPID() as CUDA events arrive.
	if t.targetPID > 0 {
		var val uint8 = 1
		if err := t.objs.TargetPids.Put(t.targetPID, val); err != nil {
			return fmt.Errorf("setting target PID %d: %w", t.targetPID, err)
		}
	}

	// Attach tracepoints.
	type tpSpec struct {
		group   string
		name    string
		prog    *ebpf.Program
	}

	// Core tracepoints — required for host correlation.
	coreSpecs := []tpSpec{
		{"sched", "sched_switch", t.objs.HandleSchedSwitch},
		{"sched", "sched_wakeup", t.objs.HandleSchedWakeup},
		{"kmem", "mm_page_alloc", t.objs.HandleMmPageAlloc},
		{"oom", "mark_victim", t.objs.HandleOomKill},
	}

	for _, spec := range coreSpecs {
		tp, err := link.Tracepoint(spec.group, spec.name, spec.prog, nil)
		if err != nil {
			return fmt.Errorf("attaching tracepoint %s/%s: %w", spec.group, spec.name, err)
		}
		t.links = append(t.links, tp)
	}

	// Process lifecycle tracepoints — optional, non-fatal on older kernels.
	optionalSpecs := []tpSpec{
		{"sched", "sched_process_exec", t.objs.HandleProcessExec},
		{"sched", "sched_process_exit", t.objs.HandleProcessExit},
		{"sched", "sched_process_fork", t.objs.HandleProcessFork},
	}

	for _, spec := range optionalSpecs {
		tp, err := link.Tracepoint(spec.group, spec.name, spec.prog, nil)
		if err != nil {
			// Non-fatal: process lifecycle tracing is optional.
			continue
		}
		t.links = append(t.links, tp)
	}

	// Create ring buffer reader for host_events map.
	t.reader, err = ringbuf.NewReader(t.objs.HostEvents)
	if err != nil {
		return fmt.Errorf("creating host ring buffer reader: %w", err)
	}

	// Create reader for critical events buffer. Available after
	// `make generate` regenerates bpf2go bindings for the new map.
	// Until then, fall back to reflection like host.go already does
	// for MmAllocAgg / SchedSwitchAgg.
	if critMap := reflectMapField(&t.objs, "CriticalEvents"); critMap != nil {
		t.criticalReader, err = ringbuf.NewReader(critMap)
		if err != nil {
			return fmt.Errorf("creating critical ring buffer reader: %w", err)
		}
	}

	closeFn = nil
	return nil
}

// SetTargetPID adds or updates a PID in the in-kernel filter map.
// This allows dynamic PID tracking without reloading the eBPF program.
func (t *Tracer) SetTargetPID(pid uint32) error {
	var val uint8 = 1
	if err := t.objs.TargetPids.Put(pid, val); err != nil {
		return fmt.Errorf("setting target PID %d: %w", pid, err)
	}
	return nil
}

// RemoveTargetPID removes a PID from the in-kernel filter map.
func (t *Tracer) RemoveTargetPID(pid uint32) error {
	if err := t.objs.TargetPids.Delete(pid); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
		return fmt.Errorf("removing target PID %d: %w", pid, err)
	}
	return nil
}

// SetTargetCGroup adds a cgroup ID to the in-kernel cgroup filter map.
// Parallel to SetTargetPID — allows K8s container scoping by cgroup v2 ID
// without fragile PID enumeration. The eBPF program checks both maps.
func (t *Tracer) SetTargetCGroup(cgroupID uint64) error {
	var val uint8 = 1
	if err := t.objs.TargetCgroups.Put(cgroupID, val); err != nil {
		return fmt.Errorf("setting target cgroup %d: %w", cgroupID, err)
	}
	return nil
}

// RemoveTargetCGroup removes a cgroup ID from the in-kernel filter map.
func (t *Tracer) RemoveTargetCGroup(cgroupID uint64) error {
	if err := t.objs.TargetCgroups.Delete(cgroupID); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
		return fmt.Errorf("removing target cgroup %d: %w", cgroupID, err)
	}
	return nil
}

// Events returns the channel on which parsed host events are delivered.
func (t *Tracer) Events() <-chan events.Event {
	return t.eventCh
}

// Run starts reading events from the eBPF ring buffer and sending them
// to the Events() channel. Blocks until ctx is cancelled.
//
// In addition to the ring buffer reader, Run launches drainAggregationMaps
// which periodically reads the mm_alloc_agg and sched_switch_agg
// PERCPU_HASH maps, emits summary events for non-target PIDs, and clears
// the maps. See drainAggregationMaps for details.
func (t *Tracer) Run(ctx context.Context) {
	defer close(t.eventCh)

	go func() {
		<-ctx.Done()
		t.reader.Close()
	}()

	// Shutdown goroutine for the critical reader. Kept separate from the
	// main reader's shutdown to avoid nil-deref when the critical map
	// isn't present (older bpf2go bindings).
	go func() {
		<-ctx.Done()
		if t.criticalReader != nil {
			t.criticalReader.Close()
		}
	}()

	go t.drainAggregationMaps(ctx)

	// Launch critical events reader goroutine. Events feed into the same
	// eventCh as the main reader — correlator uses timestamps so ordering
	// is preserved. Critical drops should always be 0; any drop logged as WARN.
	if t.criticalReader != nil {
		go t.runCriticalReader(ctx)
	}

	for {
		record, err := t.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			t.readErrors.Add(1)
			continue
		}

		evt, err := parseEvent(record.RawSample)
		if err != nil {
			t.parseErrors.Add(1)
			continue
		}

		select {
		case t.eventCh <- evt:
		default:
			t.dropped.Add(1)
		}
	}
}

// runCriticalReader reads events from the critical_events ring buffer
// and sends them to eventCh. Unlike the normal-path reader, this send
// BLOCKS when eventCh is full rather than dropping. Critical events
// (OOM, process exec/fork/exit) are guaranteed delivery — dropping them
// silently breaks downstream correlation (the walker's fork-inheritance
// path, orchestrator remediation, OOM causal chains, etc.).
//
// The only exit condition is ctx.Done() — if the consumer wedges
// permanently, we'll block here indefinitely, but a wedged eventCh
// already means the trace is broken. This is strictly safer than
// dropping critical signals on transient bursts (e.g., fork storms
// from torch.multiprocessing, rapid subprocess spawning, etc.).
func (t *Tracer) runCriticalReader(ctx context.Context) {
	for {
		record, err := t.criticalReader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			t.readErrors.Add(1)
			continue
		}
		evt, perr := parseEvent(record.RawSample)
		if perr != nil {
			t.parseErrors.Add(1)
			continue
		}
		select {
		case t.eventCh <- evt:
		case <-ctx.Done():
			return
		}
	}
}

// CriticalDropped returns the count of critical events that could not
// be delivered to the event channel. Any non-zero value is a failure
// — critical events (OOM, process lifecycle) are guaranteed delivery.
func (t *Tracer) CriticalDropped() uint64 {
	return t.criticalDropped.Load()
}

// parseEvent converts raw bytes from the ring buffer into a typed Event.
// The ring buffer delivers bytes matching the C struct host_event layout.
func parseEvent(raw []byte) (events.Event, error) {
	eventSize := int(unsafe.Sizeof(hostTraceHostEvent{}))
	if len(raw) < eventSize {
		return events.Event{}, fmt.Errorf("host event too short: %d bytes, need %d", len(raw), eventSize)
	}

	he := (*hostTraceHostEvent)(unsafe.Pointer(&raw[0]))

	// For mm_page_alloc, duration_ns carries the allocation size in bytes.
	// We store it in Args[0] and set Duration to 0.
	var dur time.Duration
	var args [2]uint64
	if he.Hdr.Op == uint8(events.HostPageAlloc) {
		args[0] = he.DurationNs // alloc_bytes
		dur = 0
	} else {
		dur = time.Duration(he.DurationNs)
	}

	// target_pid goes in Args[1] for sched events.
	// For sched_switch: this is prev_pid (the process that was running
	// before the target resumed — the most recent preemptor).
	args[1] = uint64(he.TargetPid)

	return events.Event{
		Timestamp: events.KtimeToWallClock(he.Hdr.TimestampNs),
		PID:       he.Hdr.Pid,
		TID:       he.Hdr.Tid,
		Comm:      events.CommToString(he.Hdr.Comm),
		Source:    events.Source(he.Hdr.Source),
		Op:        he.Hdr.Op,
		Duration:  dur,
		GPUID:     0,
		Args:      args,
		RetCode:   0,
		CGroupID:  he.Hdr.CgroupId,
	}, nil
}

// drainAggregationMaps periodically reads the mm_alloc_agg and
// sched_switch_agg BPF maps, emits summary events to eventCh, and
// clears the maps. Called from Run() as a goroutine.
//
// Period: drainTickInterval (1 second). Summary events use
// HostMmPageAllocSummary and HostSchedSwitchSummary ops with aggregated
// counts in Args[]. See pkg/events/types.go for the argument packing
// conventions.
//
// Returns immediately when ctx is cancelled.
func (t *Tracer) drainAggregationMaps(ctx context.Context) {
	ticker := time.NewTicker(drainTickInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			t.drainMmAlloc(ctx)
			t.drainSchedSwitch(ctx)
		}
	}
}

// aggregationMaps returns the two aggregation maps if they exist in the
// loaded objects. Older bpf2go bindings (pre-regeneration) will not expose
// these fields, so we look them up reflectively via the reserved map name
// in t.objs.hostTraceMaps. We keep this as a method so drainMmAlloc /
// drainSchedSwitch can be exercised in unit tests with nil maps.
func (t *Tracer) aggregationMaps() (mmAgg, schedAgg *ebpf.Map) {
	return lookupAggMap(&t.objs, "MmAllocAgg"), lookupAggMap(&t.objs, "SchedSwitchAgg")
}

// lookupAggMap resolves an aggregation map by field name via reflection.
// Returns nil if the field is absent (e.g., bindings haven't been
// regenerated yet) or the field value is nil. This keeps the Go code
// compatible with the current bpf2go bindings while allowing a smooth
// transition once `make generate` is run.
func lookupAggMap(objs *hostTraceObjects, fieldName string) *ebpf.Map {
	// Use reflect via unsafe-free path: direct field access is not
	// possible if the generated struct lacks the field. We fall back to
	// the "reflect" package only here and only at startup frequency (1Hz)
	// — cost is negligible.
	return reflectMapField(objs, fieldName)
}

// drainMmAlloc reads every entry in the mm_alloc_agg PERCPU_HASH map,
// sums per-CPU values into a single mmAllocStats, emits one
// HostMmPageAllocSummary event per PID, and deletes the entry.
//
// The drain is best-effort: if emission fails (full channel) we still
// delete the map entry to avoid unbounded growth. Failures are counted
// via t.dropped (same counter as ring buffer drops, since they represent
// the same loss — data that made it to userspace but not to downstream).
func (t *Tracer) drainMmAlloc(ctx context.Context) {
	mmAgg, _ := t.aggregationMaps()
	if mmAgg == nil {
		return
	}

	numCPU := runtime.NumCPU()
	perCPU := make([]mmAllocStats, numCPU)
	var key uint32
	iter := mmAgg.Iterate()
	var keysToDelete []uint32

	for iter.Next(&key, &perCPU) {
		var agg mmAllocStats
		var latestTs uint64
		for _, v := range perCPU {
			agg.Count += v.Count
			agg.TotalBytes += v.TotalBytes
			if v.LastTs > latestTs {
				latestTs = v.LastTs
			}
		}
		agg.LastTs = latestTs
		keysToDelete = append(keysToDelete, key)

		if agg.Count == 0 {
			continue
		}

		evt := events.Event{
			Timestamp: events.KtimeToWallClock(agg.LastTs),
			PID:       key,
			TID:       0,
			Source:    events.SourceHost,
			Op:        uint8(events.HostMmPageAllocSummary),
			Args:      [2]uint64{agg.Count, agg.TotalBytes},
		}

		select {
		case t.eventCh <- evt:
		case <-ctx.Done():
			return
		default:
			t.dropped.Add(1)
		}
	}
	if err := iter.Err(); err != nil {
		slog.Debug("mm_alloc_agg iterate error", "err", err)
	}

	for _, k := range keysToDelete {
		if err := mmAgg.Delete(k); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
			slog.Debug("mm_alloc_agg delete error", "pid", k, "err", err)
		}
	}
}

// drainSchedSwitch drains sched_switch_agg analogously to drainMmAlloc,
// emitting one HostSchedSwitchSummary event per (prev_pid, next_pid)
// transition. The composite key is unpacked into PID (next_pid) and
// TID (prev_pid) per the convention documented in pkg/events/types.go.
func (t *Tracer) drainSchedSwitch(ctx context.Context) {
	_, schedAgg := t.aggregationMaps()
	if schedAgg == nil {
		return
	}

	numCPU := runtime.NumCPU()
	perCPU := make([]schedSwitchStats, numCPU)
	var key uint64
	iter := schedAgg.Iterate()
	var keysToDelete []uint64

	for iter.Next(&key, &perCPU) {
		var agg schedSwitchStats
		var latestTs uint64
		for _, v := range perCPU {
			agg.Count += v.Count
			agg.TotalOffCPUNs += v.TotalOffCPUNs
			if v.LastTs > latestTs {
				latestTs = v.LastTs
			}
		}
		agg.LastTs = latestTs
		keysToDelete = append(keysToDelete, key)

		if agg.Count == 0 {
			continue
		}

		prevPID := uint32(key >> 32)
		nextPID := uint32(key & 0xffffffff)

		evt := events.Event{
			Timestamp: events.KtimeToWallClock(agg.LastTs),
			PID:       nextPID,
			TID:       prevPID,
			Source:    events.SourceHost,
			Op:        uint8(events.HostSchedSwitchSummary),
			Args:      [2]uint64{agg.Count, agg.TotalOffCPUNs},
		}

		select {
		case t.eventCh <- evt:
		case <-ctx.Done():
			return
		default:
			t.dropped.Add(1)
		}
	}
	if err := iter.Err(); err != nil {
		slog.Debug("sched_switch_agg iterate error", "err", err)
	}

	for _, k := range keysToDelete {
		if err := schedAgg.Delete(k); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
			slog.Debug("sched_switch_agg delete error", "key", k, "err", err)
		}
	}
}

// Close releases all eBPF resources. Safe to call multiple times (idempotent).
func (t *Tracer) Close() error {
	if t.closed.Swap(true) {
		return nil
	}

	var errs []error
	if t.reader != nil {
		if err := t.reader.Close(); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errs = append(errs, err)
		}
	}
	if t.criticalReader != nil {
		if err := t.criticalReader.Close(); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errs = append(errs, err)
		}
	}
	for _, l := range t.links {
		if err := l.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	t.links = nil
	if err := t.objs.Close(); err != nil {
		errs = append(errs, fmt.Errorf("closing host eBPF objects: %w", err))
	}
	return errors.Join(errs...)
}

// Dropped returns the number of events dropped due to a full channel.
func (t *Tracer) Dropped() uint64 {
	return t.dropped.Load()
}

// ReadErrors returns the number of ring buffer read errors.
func (t *Tracer) ReadErrors() uint64 {
	return t.readErrors.Load()
}

// ParseErrors returns the number of malformed events that failed to parse.
func (t *Tracer) ParseErrors() uint64 {
	return t.parseErrors.Load()
}
