// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package blockio

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ioTraceIngeroIoEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
		Comm        [16]int8
	}
	DurationNs uint64
	Dev        uint32
	NrSector   uint32
	Sector     uint64
	Rwbs       uint8
	PadIo      [7]uint8
}

type ioTraceIoReqKey struct {
	_      structs.HostLayout
	Dev    uint32
	Pad    uint32
	Sector uint64
}

type ioTraceIoReqVal struct {
	_           structs.HostLayout
	TimestampNs uint64
	CgroupId    uint64
	Pid         uint32
	Tid         uint32
	NrSector    uint32
	Rwbs        uint8
	Pad         [3]uint8
	Comm        [16]int8
}

// loadIoTrace returns the embedded CollectionSpec for ioTrace.
func loadIoTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IoTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ioTrace: %w", err)
	}

	return spec, err
}

// loadIoTraceObjects loads ioTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ioTraceObjects
//	*ioTracePrograms
//	*ioTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIoTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIoTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ioTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioTraceSpecs struct {
	ioTraceProgramSpecs
	ioTraceMapSpecs
	ioTraceVariableSpecs
}

// ioTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioTraceProgramSpecs struct {
	HandleBlockRqComplete *ebpf.ProgramSpec `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.ProgramSpec `ebpf:"handle_block_rq_issue"`
}

// ioTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioTraceMapSpecs struct {
	IngeroWatchdog *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	IoEvents       *ebpf.MapSpec `ebpf:"io_events"`
	IoInflight     *ebpf.MapSpec `ebpf:"io_inflight"`
}

// ioTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioTraceVariableSpecs struct {
	UnusedIoEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_io_event_force_btf"`
}

// ioTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIoTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioTraceObjects struct {
	ioTracePrograms
	ioTraceMaps
	ioTraceVariables
}

func (o *ioTraceObjects) Close() error {
	return _IoTraceClose(
		&o.ioTracePrograms,
		&o.ioTraceMaps,
	)
}

// ioTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIoTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioTraceMaps struct {
	IngeroWatchdog *ebpf.Map `ebpf:"ingero_watchdog"`
	IoEvents       *ebpf.Map `ebpf:"io_events"`
	IoInflight     *ebpf.Map `ebpf:"io_inflight"`
}

func (m *ioTraceMaps) Close() error {
	return _IoTraceClose(
		m.IngeroWatchdog,
		m.IoEvents,
		m.IoInflight,
	)
}

// ioTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIoTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioTraceVariables struct {
	UnusedIoEventForceBtf *ebpf.Variable `ebpf:"_unused_io_event_force_btf"`
}

// ioTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIoTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioTracePrograms struct {
	HandleBlockRqComplete *ebpf.Program `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.Program `ebpf:"handle_block_rq_issue"`
}

func (p *ioTracePrograms) Close() error {
	return _IoTraceClose(
		p.HandleBlockRqComplete,
		p.HandleBlockRqIssue,
	)
}

func _IoTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iotrace_bpfel.o
var _IoTraceBytes []byte
