package cuda

import (
	"context"
	"errors"
	"fmt"
	"sync/atomic"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/ingero-io/ingero/pkg/events"
)

// Tracer attaches eBPF uprobes to CUDA Runtime API functions and streams
// events to a Go channel.
type Tracer struct {
	libPath      string               // path to libcudart.so
	stackEnabled bool                 // capture userspace stack traces
	objs         cudaTraceObjects     // generated by bpf2go: maps + programs
	links        []link.Link          // attached probes (must Close on shutdown)
	reader       *ringbuf.Reader      // reads events from kernel ring buffer
	eventCh      chan events.Event     // output channel for parsed events
	dropped      atomic.Uint64        // events dropped due to full channel
	readErrors   atomic.Uint64        // ring buffer read errors
	parseErrors  atomic.Uint64        // event parse failures
	closed       atomic.Bool          // prevents double-close
}

// Option configures a Tracer.
type Option func(*Tracer)

// probeSpec defines a uprobe/uretprobe pair to attach to a CUDA function.
type probeSpec struct {
	symbol     string              // ELF symbol name in libcudart.so
	uprobe     *ebpf.Program       // entry probe (captures args + timestamp)
	uretprobe  *ebpf.Program       // return probe (captures retval + duration)
}

// WithStackCapture enables userspace stack trace capture in eBPF.
// When enabled, uretprobes call bpf_get_stack(BPF_F_USER_STACK) and emit
// 576-byte events (vs 56-byte base). Adds ~1us/event eBPF overhead.
func WithStackCapture(enabled bool) Option {
	return func(t *Tracer) {
		t.stackEnabled = enabled
	}
}

// New creates a new CUDA tracer for the given libcudart.so path.
// Call Attach() to start tracing, then read events from Events() channel.
func New(libcudartPath string, opts ...Option) *Tracer {
	t := &Tracer{
		libPath: libcudartPath,
		eventCh: make(chan events.Event, 4096),
	}
	for _, opt := range opts {
		opt(t)
	}
	return t
}

// Attach loads the eBPF program and attaches uprobes to CUDA functions.
func (t *Tracer) Attach() error {
	// Load the compiled eBPF program into the kernel.
	// This is where the verifier checks our C code.
	if err := loadCudaTraceObjects(&t.objs, nil); err != nil {
		return fmt.Errorf("loading eBPF objects: %w", err)
	}

	// If anything below fails, clean up accumulated links + loaded objects.
	var closeFn func()
	closeFn = func() {
		for _, l := range t.links {
			l.Close()
		}
		t.links = nil
		t.objs.Close()
	}
	defer func() {
		if closeFn != nil {
			closeFn()
		}
	}()

	exe, err := link.OpenExecutable(t.libPath)
	if err != nil {
		return fmt.Errorf("opening %s: %w", t.libPath, err)
	}

	// Define all probes to attach.
	specs := []probeSpec{
		{"cudaMalloc", t.objs.UprobeCudaMalloc, t.objs.UretprobeCudaMalloc},
		{"cudaLaunchKernel", t.objs.UprobeCudaLaunchKernel, t.objs.UretprobeCudaLaunchKernel},
		{"cudaMemcpy", t.objs.UprobeCudaMemcpy, t.objs.UretprobeCudaMemcpy},
		{"cudaMemcpyAsync", t.objs.UprobeCudaMemcpyAsync, t.objs.UretprobeCudaMemcpyAsync},
		{"cudaStreamSynchronize", t.objs.UprobeCudaStreamSync, t.objs.UretprobeCudaStreamSync},
		{"cudaDeviceSynchronize", t.objs.UprobeCudaDeviceSync, t.objs.UretprobeCudaDeviceSync},
	}

	// Attach each uprobe/uretprobe pair.
	for _, spec := range specs {
		// Attach entry probe
		up, err := exe.Uprobe(spec.symbol, spec.uprobe, nil)
		if err != nil {
			return fmt.Errorf("attaching uprobe to %s: %w", spec.symbol, err)
		}
		t.links = append(t.links, up)

		// Attach return probe
		uret, err := exe.Uretprobe(spec.symbol, spec.uretprobe, nil)
		if err != nil {
			return fmt.Errorf("attaching uretprobe to %s: %w", spec.symbol, err)
		}
		t.links = append(t.links, uret)
	}

	// Enable stack capture in the eBPF config map if requested.
	if t.stackEnabled && t.objs.ConfigMap != nil {
		// ingero_config: { uint8 capture_stack, uint8[7] pad }
		cfg := [8]byte{1}
		if err := t.objs.ConfigMap.Put(uint32(0), cfg[:]); err != nil {
			return fmt.Errorf("enabling stack capture: %w", err)
		}
	}

	// Create ring buffer reader.
	t.reader, err = ringbuf.NewReader(t.objs.Events)
	if err != nil {
		return fmt.Errorf("creating ring buffer reader: %w", err)
	}

	// Success — don't clean up.
	closeFn = nil
	return nil
}

// Events returns a read-only channel on which parsed CUDA events are delivered.
func (t *Tracer) Events() <-chan events.Event {
	return t.eventCh
}

// Run starts reading events from the eBPF ring buffer and sending them
// to the Events() channel. Blocks until ctx is cancelled.
func (t *Tracer) Run(ctx context.Context) {
	defer close(t.eventCh)

	// When context is cancelled, close the reader to unblock Read().
	go func() {
		<-ctx.Done()
		t.reader.Close()
	}()

	for {
		record, err := t.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return // Clean shutdown
			}
			t.readErrors.Add(1)
			continue // Transient error, skip
		}

		evt, err := parseEvent(record.RawSample)
		if err != nil {
			t.parseErrors.Add(1)
			continue // Malformed event, skip
		}

		// Non-blocking send — drop event if channel is full.
		// This prevents the reader goroutine from blocking if the
		// consumer is slow. Better to drop events than stall tracing.
		select {
		case t.eventCh <- evt:
		default:
			t.dropped.Add(1)
		}
	}
}

// stackEventSize is sizeof(cuda_event_stack) — base event + stack section.
// Layout: 56 (base) + 2 (stack_depth) + 6 (pad) + 512 (64 * uint64 IPs) = 576.
const stackEventSize = 576

// parseEvent converts raw bytes from the ring buffer into a typed Event.
// Handles both base events (56 bytes) and stack events (576 bytes).
//
// The Go parser distinguishes by record length:
//   - 56 bytes  → cuda_event (no stack)
//   - 576 bytes → cuda_event_stack (with stack trace)
func parseEvent(raw []byte) (events.Event, error) {
	baseSize := int(unsafe.Sizeof(cudaTraceCudaEvent{}))
	if len(raw) < baseSize {
		return events.Event{}, fmt.Errorf("event too short: %d bytes, need %d", len(raw), baseSize)
	}

	// Zero-copy parse of the base event fields (same layout for both sizes).
	ce := (*cudaTraceCudaEvent)(unsafe.Pointer(&raw[0]))

	evt := events.Event{
		Timestamp: events.KtimeToWallClock(ce.Hdr.TimestampNs),
		PID:       ce.Hdr.Pid,
		TID:       ce.Hdr.Tid,
		Source:    events.Source(ce.Hdr.Source),
		Op:        ce.Hdr.Op,
		Duration:  time.Duration(ce.DurationNs),
		GPUID:     ce.GpuId,
		Args:      [2]uint64{ce.Arg0, ce.Arg1},
		RetCode:   ce.ReturnCode,
	}

	// Check for stack event (576 bytes).
	if len(raw) >= stackEventSize {
		evt.Stack = events.ParseStackIPs(raw, baseSize)
	}

	return evt, nil
}

// Close releases all eBPF resources. Safe to call multiple times (idempotent).
// Closes in reverse order: reader → links → objects.
func (t *Tracer) Close() error {
	if t.closed.Swap(true) {
		return nil // Already closed
	}

	var errs []error
	if t.reader != nil {
		if err := t.reader.Close(); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errs = append(errs, err)
		}
	}
	for _, l := range t.links {
		if err := l.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	t.links = nil
	if err := t.objs.Close(); err != nil {
		errs = append(errs, fmt.Errorf("closing eBPF objects: %w", err))
	}
	return errors.Join(errs...)
}

// LibPath returns the path to the libcudart.so being traced.
func (t *Tracer) LibPath() string {
	return t.libPath
}

// ProbeCount returns the number of attached probes.
func (t *Tracer) ProbeCount() int {
	return len(t.links)
}

// Dropped returns the number of events dropped due to a full channel.
// This is an atomic counter — safe to call from any goroutine.
func (t *Tracer) Dropped() uint64 {
	return t.dropped.Load()
}

// ReadErrors returns the number of ring buffer read errors (transient kernel-side failures).
func (t *Tracer) ReadErrors() uint64 {
	return t.readErrors.Load()
}

// ParseErrors returns the number of malformed events that failed to parse.
func (t *Tracer) ParseErrors() uint64 {
	return t.parseErrors.Load()
}
