// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package cuda

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cudaTraceCudaEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		_           [4]byte
	}
	DurationNs uint64
	Arg0       uint64
	Arg1       uint64
	ReturnCode int32
	GpuId      uint32
}

type cudaTraceEntryState struct {
	_           structs.HostLayout
	TimestampNs uint64
	Op          uint8
	Pad         [7]uint8
	Arg0        uint64
	Arg1        uint64
}

type cudaTraceIngeroConfig struct {
	_            structs.HostLayout
	CaptureStack uint8
	Pad          [7]uint8
}

// loadCudaTrace returns the embedded CollectionSpec for cudaTrace.
func loadCudaTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CudaTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cudaTrace: %w", err)
	}

	return spec, err
}

// loadCudaTraceObjects loads cudaTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cudaTraceObjects
//	*cudaTracePrograms
//	*cudaTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCudaTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCudaTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cudaTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceSpecs struct {
	cudaTraceProgramSpecs
	cudaTraceMapSpecs
	cudaTraceVariableSpecs
}

// cudaTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceProgramSpecs struct {
	UprobeCudaDeviceSync      *ebpf.ProgramSpec `ebpf:"uprobe_cuda_device_sync"`
	UprobeCudaFree            *ebpf.ProgramSpec `ebpf:"uprobe_cuda_free"`
	UprobeCudaLaunchKernel    *ebpf.ProgramSpec `ebpf:"uprobe_cuda_launch_kernel"`
	UprobeCudaMalloc          *ebpf.ProgramSpec `ebpf:"uprobe_cuda_malloc"`
	UprobeCudaMemcpy          *ebpf.ProgramSpec `ebpf:"uprobe_cuda_memcpy"`
	UprobeCudaMemcpyAsync     *ebpf.ProgramSpec `ebpf:"uprobe_cuda_memcpy_async"`
	UprobeCudaStreamSync      *ebpf.ProgramSpec `ebpf:"uprobe_cuda_stream_sync"`
	UretprobeCudaDeviceSync   *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_device_sync"`
	UretprobeCudaFree         *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_free"`
	UretprobeCudaLaunchKernel *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_launch_kernel"`
	UretprobeCudaMalloc       *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_malloc"`
	UretprobeCudaMemcpy       *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_memcpy"`
	UretprobeCudaMemcpyAsync  *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_memcpy_async"`
	UretprobeCudaStreamSync   *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_stream_sync"`
}

// cudaTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceMapSpecs struct {
	ConfigMap *ebpf.MapSpec `ebpf:"config_map"`
	EntryMap  *ebpf.MapSpec `ebpf:"entry_map"`
	Events    *ebpf.MapSpec `ebpf:"events"`
}

// cudaTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceVariableSpecs struct {
	UnusedConfigForceBtf         *ebpf.VariableSpec `ebpf:"_unused_config_force_btf"`
	UnusedCudaEventForceBtf      *ebpf.VariableSpec `ebpf:"_unused_cuda_event_force_btf"`
	UnusedCudaEventStackForceBtf *ebpf.VariableSpec `ebpf:"_unused_cuda_event_stack_force_btf"`
}

// cudaTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTraceObjects struct {
	cudaTracePrograms
	cudaTraceMaps
	cudaTraceVariables
}

func (o *cudaTraceObjects) Close() error {
	return _CudaTraceClose(
		&o.cudaTracePrograms,
		&o.cudaTraceMaps,
	)
}

// cudaTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTraceMaps struct {
	ConfigMap *ebpf.Map `ebpf:"config_map"`
	EntryMap  *ebpf.Map `ebpf:"entry_map"`
	Events    *ebpf.Map `ebpf:"events"`
}

func (m *cudaTraceMaps) Close() error {
	return _CudaTraceClose(
		m.ConfigMap,
		m.EntryMap,
		m.Events,
	)
}

// cudaTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTraceVariables struct {
	UnusedConfigForceBtf         *ebpf.Variable `ebpf:"_unused_config_force_btf"`
	UnusedCudaEventForceBtf      *ebpf.Variable `ebpf:"_unused_cuda_event_force_btf"`
	UnusedCudaEventStackForceBtf *ebpf.Variable `ebpf:"_unused_cuda_event_stack_force_btf"`
}

// cudaTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTracePrograms struct {
	UprobeCudaDeviceSync      *ebpf.Program `ebpf:"uprobe_cuda_device_sync"`
	UprobeCudaFree            *ebpf.Program `ebpf:"uprobe_cuda_free"`
	UprobeCudaLaunchKernel    *ebpf.Program `ebpf:"uprobe_cuda_launch_kernel"`
	UprobeCudaMalloc          *ebpf.Program `ebpf:"uprobe_cuda_malloc"`
	UprobeCudaMemcpy          *ebpf.Program `ebpf:"uprobe_cuda_memcpy"`
	UprobeCudaMemcpyAsync     *ebpf.Program `ebpf:"uprobe_cuda_memcpy_async"`
	UprobeCudaStreamSync      *ebpf.Program `ebpf:"uprobe_cuda_stream_sync"`
	UretprobeCudaDeviceSync   *ebpf.Program `ebpf:"uretprobe_cuda_device_sync"`
	UretprobeCudaFree         *ebpf.Program `ebpf:"uretprobe_cuda_free"`
	UretprobeCudaLaunchKernel *ebpf.Program `ebpf:"uretprobe_cuda_launch_kernel"`
	UretprobeCudaMalloc       *ebpf.Program `ebpf:"uretprobe_cuda_malloc"`
	UretprobeCudaMemcpy       *ebpf.Program `ebpf:"uretprobe_cuda_memcpy"`
	UretprobeCudaMemcpyAsync  *ebpf.Program `ebpf:"uretprobe_cuda_memcpy_async"`
	UretprobeCudaStreamSync   *ebpf.Program `ebpf:"uretprobe_cuda_stream_sync"`
}

func (p *cudaTracePrograms) Close() error {
	return _CudaTraceClose(
		p.UprobeCudaDeviceSync,
		p.UprobeCudaFree,
		p.UprobeCudaLaunchKernel,
		p.UprobeCudaMalloc,
		p.UprobeCudaMemcpy,
		p.UprobeCudaMemcpyAsync,
		p.UprobeCudaStreamSync,
		p.UretprobeCudaDeviceSync,
		p.UretprobeCudaFree,
		p.UretprobeCudaLaunchKernel,
		p.UretprobeCudaMalloc,
		p.UretprobeCudaMemcpy,
		p.UretprobeCudaMemcpyAsync,
		p.UretprobeCudaStreamSync,
	)
}

func _CudaTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cudatrace_bpfel.o
var _CudaTraceBytes []byte
