// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package cuda

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cudaTraceAllocKey struct {
	_      structs.HostLayout
	Pid    uint32
	Pad    uint32
	DevPtr uint64
}

type cudaTraceCudaEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
		Comm        [16]int8
	}
	DurationNs uint64
	Arg0       uint64
	Arg1       uint64
	ReturnCode int32
	GpuId      uint32
}

type cudaTraceEntryState struct {
	_           structs.HostLayout
	TimestampNs uint64
	Op          uint8
	Pad         [7]uint8
	Arg0        uint64
	Arg1        uint64
}

type cudaTraceIngeroConfig struct {
	_            structs.HostLayout
	CaptureStack uint8
	Pad1         [3]uint8
	SamplingRate uint32
	Pad2         uint32
}

type cudaTracePyRuntimeState struct {
	_                          structs.HostLayout
	RuntimeAddr                uint64
	OffRuntimeInterpretersHead uint16
	OffTstateHead              uint16
	OffTstateNext              uint16
	OffTstateNativeTid         uint16
	OffTstateFrame             uint16
	OffFrameBack               uint16
	OffFrameCode               uint16
	OffCodeFilename            uint16
	OffCodeName                uint16
	OffCodeFirstlineno         uint16
	OffUnicodeState            uint16
	OffUnicodeData             uint16
	PythonMinor                uint8
	Pad3                       uint8
	OffCframeCurrentFrame      uint16
	_                          [4]byte
}

type cudaTracePyWalkResult struct {
	_         structs.HostLayout
	Depth     uint8
	Truncated uint8
	Pad       [6]uint8
	Frames    [16]struct {
		_           structs.HostLayout
		Filename    [128]int8
		Funcname    [128]int8
		Firstlineno int32
		Pad         uint32
	}
}

// loadCudaTrace returns the embedded CollectionSpec for cudaTrace.
func loadCudaTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CudaTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cudaTrace: %w", err)
	}

	return spec, err
}

// loadCudaTraceObjects loads cudaTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cudaTraceObjects
//	*cudaTracePrograms
//	*cudaTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCudaTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCudaTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cudaTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceSpecs struct {
	cudaTraceProgramSpecs
	cudaTraceMapSpecs
	cudaTraceVariableSpecs
}

// cudaTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceProgramSpecs struct {
	UprobeCudaDeviceSync       *ebpf.ProgramSpec `ebpf:"uprobe_cuda_device_sync"`
	UprobeCudaFree             *ebpf.ProgramSpec `ebpf:"uprobe_cuda_free"`
	UprobeCudaLaunchKernel     *ebpf.ProgramSpec `ebpf:"uprobe_cuda_launch_kernel"`
	UprobeCudaMalloc           *ebpf.ProgramSpec `ebpf:"uprobe_cuda_malloc"`
	UprobeCudaMallocManaged    *ebpf.ProgramSpec `ebpf:"uprobe_cuda_malloc_managed"`
	UprobeCudaMemcpy           *ebpf.ProgramSpec `ebpf:"uprobe_cuda_memcpy"`
	UprobeCudaMemcpyAsync      *ebpf.ProgramSpec `ebpf:"uprobe_cuda_memcpy_async"`
	UprobeCudaStreamSync       *ebpf.ProgramSpec `ebpf:"uprobe_cuda_stream_sync"`
	UretprobeCudaDeviceSync    *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_device_sync"`
	UretprobeCudaFree          *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_free"`
	UretprobeCudaLaunchKernel  *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_launch_kernel"`
	UretprobeCudaMalloc        *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_malloc"`
	UretprobeCudaMallocManaged *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_malloc_managed"`
	UretprobeCudaMemcpy        *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_memcpy"`
	UretprobeCudaMemcpyAsync   *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_memcpy_async"`
	UretprobeCudaStreamSync    *ebpf.ProgramSpec `ebpf:"uretprobe_cuda_stream_sync"`
}

// cudaTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceMapSpecs struct {
	AllocSizes     *ebpf.MapSpec `ebpf:"alloc_sizes"`
	ConfigMap      *ebpf.MapSpec `ebpf:"config_map"`
	EntryMap       *ebpf.MapSpec `ebpf:"entry_map"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	IngeroWatchdog *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	PyDebugStats   *ebpf.MapSpec `ebpf:"py_debug_stats"`
	PyRuntimeMap   *ebpf.MapSpec `ebpf:"py_runtime_map"`
	PyScratch      *ebpf.MapSpec `ebpf:"py_scratch"`
	SampleCounter  *ebpf.MapSpec `ebpf:"sample_counter"`
}

// cudaTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cudaTraceVariableSpecs struct {
	UnusedConfigForceBtf           *ebpf.VariableSpec `ebpf:"_unused_config_force_btf"`
	UnusedCudaEventForceBtf        *ebpf.VariableSpec `ebpf:"_unused_cuda_event_force_btf"`
	UnusedCudaEventStackForceBtf   *ebpf.VariableSpec `ebpf:"_unused_cuda_event_stack_force_btf"`
	UnusedCudaEventStackPyForceBtf *ebpf.VariableSpec `ebpf:"_unused_cuda_event_stack_py_force_btf"`
	UnusedPyFrameForceBtf          *ebpf.VariableSpec `ebpf:"_unused_py_frame_force_btf"`
	UnusedPyRuntimeStateForceBtf   *ebpf.VariableSpec `ebpf:"_unused_py_runtime_state_force_btf"`
	UnusedPyWalkResultForceBtf     *ebpf.VariableSpec `ebpf:"_unused_py_walk_result_force_btf"`
}

// cudaTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTraceObjects struct {
	cudaTracePrograms
	cudaTraceMaps
	cudaTraceVariables
}

func (o *cudaTraceObjects) Close() error {
	return _CudaTraceClose(
		&o.cudaTracePrograms,
		&o.cudaTraceMaps,
	)
}

// cudaTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTraceMaps struct {
	AllocSizes     *ebpf.Map `ebpf:"alloc_sizes"`
	ConfigMap      *ebpf.Map `ebpf:"config_map"`
	EntryMap       *ebpf.Map `ebpf:"entry_map"`
	Events         *ebpf.Map `ebpf:"events"`
	IngeroWatchdog *ebpf.Map `ebpf:"ingero_watchdog"`
	PyDebugStats   *ebpf.Map `ebpf:"py_debug_stats"`
	PyRuntimeMap   *ebpf.Map `ebpf:"py_runtime_map"`
	PyScratch      *ebpf.Map `ebpf:"py_scratch"`
	SampleCounter  *ebpf.Map `ebpf:"sample_counter"`
}

func (m *cudaTraceMaps) Close() error {
	return _CudaTraceClose(
		m.AllocSizes,
		m.ConfigMap,
		m.EntryMap,
		m.Events,
		m.IngeroWatchdog,
		m.PyDebugStats,
		m.PyRuntimeMap,
		m.PyScratch,
		m.SampleCounter,
	)
}

// cudaTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTraceVariables struct {
	UnusedConfigForceBtf           *ebpf.Variable `ebpf:"_unused_config_force_btf"`
	UnusedCudaEventForceBtf        *ebpf.Variable `ebpf:"_unused_cuda_event_force_btf"`
	UnusedCudaEventStackForceBtf   *ebpf.Variable `ebpf:"_unused_cuda_event_stack_force_btf"`
	UnusedCudaEventStackPyForceBtf *ebpf.Variable `ebpf:"_unused_cuda_event_stack_py_force_btf"`
	UnusedPyFrameForceBtf          *ebpf.Variable `ebpf:"_unused_py_frame_force_btf"`
	UnusedPyRuntimeStateForceBtf   *ebpf.Variable `ebpf:"_unused_py_runtime_state_force_btf"`
	UnusedPyWalkResultForceBtf     *ebpf.Variable `ebpf:"_unused_py_walk_result_force_btf"`
}

// cudaTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCudaTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cudaTracePrograms struct {
	UprobeCudaDeviceSync       *ebpf.Program `ebpf:"uprobe_cuda_device_sync"`
	UprobeCudaFree             *ebpf.Program `ebpf:"uprobe_cuda_free"`
	UprobeCudaLaunchKernel     *ebpf.Program `ebpf:"uprobe_cuda_launch_kernel"`
	UprobeCudaMalloc           *ebpf.Program `ebpf:"uprobe_cuda_malloc"`
	UprobeCudaMallocManaged    *ebpf.Program `ebpf:"uprobe_cuda_malloc_managed"`
	UprobeCudaMemcpy           *ebpf.Program `ebpf:"uprobe_cuda_memcpy"`
	UprobeCudaMemcpyAsync      *ebpf.Program `ebpf:"uprobe_cuda_memcpy_async"`
	UprobeCudaStreamSync       *ebpf.Program `ebpf:"uprobe_cuda_stream_sync"`
	UretprobeCudaDeviceSync    *ebpf.Program `ebpf:"uretprobe_cuda_device_sync"`
	UretprobeCudaFree          *ebpf.Program `ebpf:"uretprobe_cuda_free"`
	UretprobeCudaLaunchKernel  *ebpf.Program `ebpf:"uretprobe_cuda_launch_kernel"`
	UretprobeCudaMalloc        *ebpf.Program `ebpf:"uretprobe_cuda_malloc"`
	UretprobeCudaMallocManaged *ebpf.Program `ebpf:"uretprobe_cuda_malloc_managed"`
	UretprobeCudaMemcpy        *ebpf.Program `ebpf:"uretprobe_cuda_memcpy"`
	UretprobeCudaMemcpyAsync   *ebpf.Program `ebpf:"uretprobe_cuda_memcpy_async"`
	UretprobeCudaStreamSync    *ebpf.Program `ebpf:"uretprobe_cuda_stream_sync"`
}

func (p *cudaTracePrograms) Close() error {
	return _CudaTraceClose(
		p.UprobeCudaDeviceSync,
		p.UprobeCudaFree,
		p.UprobeCudaLaunchKernel,
		p.UprobeCudaMalloc,
		p.UprobeCudaMallocManaged,
		p.UprobeCudaMemcpy,
		p.UprobeCudaMemcpyAsync,
		p.UprobeCudaStreamSync,
		p.UretprobeCudaDeviceSync,
		p.UretprobeCudaFree,
		p.UretprobeCudaLaunchKernel,
		p.UretprobeCudaMalloc,
		p.UretprobeCudaMallocManaged,
		p.UretprobeCudaMemcpy,
		p.UretprobeCudaMemcpyAsync,
		p.UretprobeCudaStreamSync,
	)
}

func _CudaTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cudatrace_bpfel.o
var _CudaTraceBytes []byte
