package cuda

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"os"
	"reflect"
	"sync/atomic"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/ingero-io/ingero/pkg/events"
)

// lookupMapField returns a *ebpf.Map field on the given map-bundle struct by
// name, or nil if the field is absent. Used so that callers can request maps
// that may not yet be present in the generated bindings (e.g., py_runtime_map
// which is emitted only after bpf2go regenerates post-walker-header-include).
func lookupMapField(maps interface{}, fieldName string) *ebpf.Map {
	v := reflect.ValueOf(maps)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return nil
	}
	f := v.FieldByName(fieldName)
	if !f.IsValid() || f.IsZero() {
		return nil
	}
	m, ok := f.Interface().(*ebpf.Map)
	if !ok {
		return nil
	}
	return m
}

const watchdogPinPath = "/sys/fs/bpf/ingero_watchdog"

// Tracer attaches eBPF uprobes to CUDA Runtime API functions and streams
// events to a Go channel.
type Tracer struct {
	libPath      string               // path to libcudart.so
	stackEnabled bool                 // capture userspace stack traces
	ringBufSize  uint32               // 0 = use compiled default
	uprobePID    int                  // >0 = attach uprobes to specific PID only
	objs         cudaTraceObjects     // generated by bpf2go: maps + programs
	links        []link.Link          // attached probes (must Close on shutdown)
	reader       *ringbuf.Reader      // reads events from kernel ring buffer
	eventCh      chan events.Event     // output channel for parsed events
	dropped      atomic.Uint64        // events dropped due to full channel
	readErrors   atomic.Uint64        // ring buffer read errors
	parseErrors  atomic.Uint64        // event parse failures
	closed       atomic.Bool          // prevents double-close
}

// Option configures a Tracer.
type Option func(*Tracer)

// probeSpec defines a uprobe/uretprobe pair to attach to a CUDA function.
type probeSpec struct {
	symbol     string              // ELF symbol name in libcudart.so
	uprobe     *ebpf.Program       // entry probe (captures args + timestamp)
	uretprobe  *ebpf.Program       // return probe (captures retval + duration)
}

// WithStackCapture enables userspace stack trace capture in eBPF.
// When enabled, uretprobes call bpf_get_stack(BPF_F_USER_STACK) and emit
// 584-byte events (vs 64-byte base). Adds ~1us/event eBPF overhead.
func WithStackCapture(enabled bool) Option {
	return func(t *Tracer) {
		t.stackEnabled = enabled
	}
}

// WithUprobePID restricts uprobes to a single target PID instead of
// system-wide (pid=-1). When set, only the specified process triggers the
// probes. Reduces kernel overhead and may work around YAMA ptrace_scope=3
// interactions that gate system-wide perf_event_open.
func WithUprobePID(pid int) Option {
	return func(t *Tracer) {
		t.uprobePID = pid
	}
}

// WithRingBufSize overrides the compiled-in ring buffer size (default 8MB).
// The value must be a power of 2 and at least 4096 (one page).
func WithRingBufSize(bytes uint32) Option {
	return func(t *Tracer) {
		t.ringBufSize = bytes
	}
}

// New creates a new CUDA tracer for the given libcudart.so path.
// Call Attach() to start tracing, then read events from Events() channel.
func New(libcudartPath string, opts ...Option) *Tracer {
	t := &Tracer{
		libPath: libcudartPath,
		eventCh: make(chan events.Event, 4096),
	}
	for _, opt := range opts {
		opt(t)
	}
	return t
}

// Attach loads the eBPF program and attaches uprobes to CUDA functions.
func (t *Tracer) Attach() error {
	// Load the eBPF spec so we can optionally override ring buffer size.
	spec, err := loadCudaTrace()
	if err != nil {
		return fmt.Errorf("loading eBPF spec: %w", err)
	}

	if t.ringBufSize > 0 {
		if eventsMap, ok := spec.Maps["events"]; ok {
			eventsMap.MaxEntries = t.ringBufSize
		}
	}

	if err := spec.LoadAndAssign(&t.objs, nil); err != nil {
		return fmt.Errorf("loading eBPF objects: %w", err)
	}

	// Pin the watchdog map so an external remediation service can open it by path.
	// Non-fatal: the watchdog is optional.
	if t.objs.IngeroWatchdog != nil {
		os.Remove(watchdogPinPath) // Remove stale pin from previous run.
		if err := t.objs.IngeroWatchdog.Pin(watchdogPinPath); err != nil {
			log.Printf("WARN: watchdog map pin failed: %v", err)
		}
	}

	// If anything below fails, clean up accumulated links + loaded objects.
	// The pin at watchdogPinPath was created above (line ~136) BEFORE this
	// deferred cleanup is registered, so we explicitly unpin on failure —
	// otherwise a mid-Attach error leaves the pin orphaned (Bug 10 variant).
	var closeFn func()
	closeFn = func() {
		for _, l := range t.links {
			l.Close()
		}
		t.links = nil
		os.Remove(watchdogPinPath)
		t.objs.Close()
	}
	defer func() {
		if closeFn != nil {
			closeFn()
		}
	}()

	exe, err := link.OpenExecutable(t.libPath)
	if err != nil {
		return fmt.Errorf("opening %s: %w", t.libPath, err)
	}

	// Define all probes to attach.
	specs := []probeSpec{
		{"cudaMalloc", t.objs.UprobeCudaMalloc, t.objs.UretprobeCudaMalloc},
		{"cudaFree", t.objs.UprobeCudaFree, t.objs.UretprobeCudaFree},
		{"cudaLaunchKernel", t.objs.UprobeCudaLaunchKernel, t.objs.UretprobeCudaLaunchKernel},
		{"cudaMemcpy", t.objs.UprobeCudaMemcpy, t.objs.UretprobeCudaMemcpy},
		{"cudaMemcpyAsync", t.objs.UprobeCudaMemcpyAsync, t.objs.UretprobeCudaMemcpyAsync},
		{"cudaStreamSynchronize", t.objs.UprobeCudaStreamSync, t.objs.UretprobeCudaStreamSync},
		{"cudaDeviceSynchronize", t.objs.UprobeCudaDeviceSync, t.objs.UretprobeCudaDeviceSync},
	}

	// PID-specific uprobe option: when uprobePID > 0, attach uprobes
	// only for that process (reduces kernel overhead, may help at
	// ptrace_scope=3 where system-wide pid=-1 uprobes can be gated).
	var uprobeOpts *link.UprobeOptions
	if t.uprobePID > 0 {
		uprobeOpts = &link.UprobeOptions{PID: t.uprobePID}
	}

	// Attach each uprobe/uretprobe pair.
	for _, spec := range specs {
		up, err := exe.Uprobe(spec.symbol, spec.uprobe, uprobeOpts)
		if err != nil {
			return fmt.Errorf("attaching uprobe to %s: %w", spec.symbol, err)
		}
		t.links = append(t.links, up)

		uret, err := exe.Uretprobe(spec.symbol, spec.uretprobe, uprobeOpts)
		if err != nil {
			return fmt.Errorf("attaching uretprobe to %s: %w", spec.symbol, err)
		}
		t.links = append(t.links, uret)
	}

	// Optional probes — non-fatal if symbol not found.
	optionalSpecs := []probeSpec{
		{"cudaMallocManaged", t.objs.UprobeCudaMallocManaged, t.objs.UretprobeCudaMallocManaged},
	}
	for _, spec := range optionalSpecs {
		up, err := exe.Uprobe(spec.symbol, spec.uprobe, uprobeOpts)
		if err != nil {
			continue
		}
		uret, err := exe.Uretprobe(spec.symbol, spec.uretprobe, uprobeOpts)
		if err != nil {
			up.Close()
			continue
		}
		t.links = append(t.links, up, uret)
	}

	// Enable stack capture in the eBPF config map if requested.
	// ingero_config is 12 bytes on x86_64 (capture_stack + pad1[3] +
	// sampling_rate + pad2 — natural u32 alignment adds no trailing
	// padding). Always write the full struct so sampling_rate is zeroed
	// to "emit all" by default until SetSamplingRate() overrides it.
	if t.stackEnabled && t.objs.ConfigMap != nil {
		var cfg [12]byte
		cfg[0] = 1 // capture_stack = 1; sampling_rate (offset 4) stays 0.
		if err := t.objs.ConfigMap.Put(uint32(0), cfg[:]); err != nil {
			return fmt.Errorf("enabling stack capture: %w", err)
		}
	}

	// Create ring buffer reader.
	t.reader, err = ringbuf.NewReader(t.objs.Events)
	if err != nil {
		return fmt.Errorf("creating ring buffer reader: %w", err)
	}

	// Success — don't clean up.
	closeFn = nil
	return nil
}

// Events returns a read-only channel on which parsed CUDA events are delivered.
func (t *Tracer) Events() <-chan events.Event {
	return t.eventCh
}

// Run starts reading events from the eBPF ring buffer and sending them
// to the Events() channel. Blocks until ctx is cancelled.
func (t *Tracer) Run(ctx context.Context) {
	defer close(t.eventCh)

	// When context is cancelled, close the reader to unblock Read().
	go func() {
		<-ctx.Done()
		t.reader.Close()
	}()

	for {
		record, err := t.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return // Clean shutdown
			}
			t.readErrors.Add(1)
			continue // Transient error, skip
		}

		evt, err := parseEvent(record.RawSample)
		if err != nil {
			t.parseErrors.Add(1)
			continue // Malformed event, skip
		}

		// Non-blocking send — drop event if channel is full.
		// This prevents the reader goroutine from blocking if the
		// consumer is slow. Better to drop events than stall tracing.
		select {
		case t.eventCh <- evt:
		default:
			t.dropped.Add(1)
		}
	}
}

// stackEventSize is sizeof(cuda_event_stack) — derived from the bpf2go-generated
// base struct size to prevent silent misparsing when BPF struct sizes change.
// Layout: base (80, v0.10 with hdr.comm; was 64) + 2 (stack_depth) + 6 (pad) + 512 (64 * uint64 IPs) = 600.
var stackEventSize = int(unsafe.Sizeof(cudaTraceCudaEvent{})) + 8 + 512 // base + depth/pad + ips

// Python walker result layout (mirrors bpf/common.bpf.h :: py_walk_result).
// Defined as compile-time constants rather than derived from bpf2go because
// py_walk_result is not currently exported via the CUDA tracer's bpf2go
// `-type` flag. If the kernel-side layout changes, update these constants
// AND the decode loop in parsePyFrames together.
const (
	pyWalkResultHeaderSize = 8                 // 1+1 + 6 pad
	pyFrameFilenameLen     = 128               // char filename[128]
	pyFrameFuncnameLen     = 128               // char funcname[128]
	pyFrameSize            = 264               // 128 + 128 + s32 + u32 pad
	pyMaxFrames            = 16                // PY_MAX_FRAMES
	pyWalkResultSize       = pyWalkResultHeaderSize + pyFrameSize*pyMaxFrames
)

// stackPyEventSize is sizeof(cuda_event_stack_py): stack record + py result.
// Today: 600 + 4232 = 4832. Used to distinguish the extended record from
// the plain stack record on the ring buffer.
var stackPyEventSize = stackEventSize + pyWalkResultSize

// ingeroEventFlagPyFrames mirrors INGERO_EVENT_FLAG_PY_FRAMES in
// bpf/common.bpf.h. Stored in ingero_event_hdr._pad (u16 on the wire;
// bpf2go maps the field to Pad uint16).
const ingeroEventFlagPyFrames uint16 = 0x0001

// parseEvent converts raw bytes from the ring buffer into a typed Event.
// Dispatches on record length and the INGERO_EVENT_FLAG_PY_FRAMES bit:
//
//	  80 bytes → cuda_event            (no stack, no python)
//	 600 bytes → cuda_event_stack      (stack only)
//	4832 bytes → cuda_event_stack_py   (stack + python; flag bit set)
func parseEvent(raw []byte) (events.Event, error) {
	baseSize := int(unsafe.Sizeof(cudaTraceCudaEvent{}))
	if len(raw) < baseSize {
		return events.Event{}, fmt.Errorf("event too short: %d bytes, need %d", len(raw), baseSize)
	}

	// Zero-copy parse of the base event fields (same layout for all sizes).
	ce := (*cudaTraceCudaEvent)(unsafe.Pointer(&raw[0]))

	evt := events.Event{
		Timestamp: events.KtimeToWallClock(ce.Hdr.TimestampNs),
		PID:       ce.Hdr.Pid,
		TID:       ce.Hdr.Tid,
		Comm:      events.CommToString(ce.Hdr.Comm),
		Source:    events.Source(ce.Hdr.Source),
		Op:        ce.Hdr.Op,
		Duration:  time.Duration(ce.DurationNs),
		GPUID:     ce.GpuId,
		Args:      [2]uint64{ce.Arg0, ce.Arg1},
		RetCode:   ce.ReturnCode,
		CGroupID:  ce.Hdr.CgroupId,
	}

	// Stack event or extended (stack + python) event — stack layout is
	// at the same offset in both variants.
	if len(raw) >= stackEventSize {
		evt.Stack = events.ParseStackIPs(raw, baseSize)
	}

	// Extended event: decode Python frames trailing after cuda_event_stack.
	// Guard on both the flag bit (set by the BPF program when attaching
	// frames) and the record length (belt-and-suspenders against partial
	// writes or future struct-layout drift).
	if (ce.Hdr.Pad&ingeroEventFlagPyFrames) != 0 && len(raw) >= stackPyEventSize {
		pyData := raw[stackEventSize : stackEventSize+pyWalkResultSize]
		evt.PythonFrames = parsePyFrames(pyData)
	}

	return evt, nil
}

// parsePyFrames decodes the trailing py_walk_result bytes produced by the
// in-kernel walker (bpf/python_walker.bpf.h). pyData MUST be exactly
// pyWalkResultSize bytes; callers are expected to slice precisely.
func parsePyFrames(pyData []byte) []events.PyFrame {
	if len(pyData) < pyWalkResultHeaderSize {
		return nil
	}
	depth := int(pyData[0])
	// pyData[1] is `truncated` — surfacing it on Event is a future
	// enhancement (would become Event.PythonFramesTruncated bool).
	// Bytes [2..8) are pad and are ignored.

	if depth <= 0 {
		return nil
	}
	if depth > pyMaxFrames {
		depth = pyMaxFrames
	}

	frames := make([]events.PyFrame, 0, depth)
	for i := 0; i < depth; i++ {
		off := pyWalkResultHeaderSize + i*pyFrameSize
		if off+pyFrameSize > len(pyData) {
			break
		}
		filename := cstring(pyData[off : off+pyFrameFilenameLen])
		funcname := cstring(pyData[off+pyFrameFilenameLen : off+pyFrameFilenameLen+pyFrameFuncnameLen])
		lineOff := off + pyFrameFilenameLen + pyFrameFuncnameLen
		line := int32(binary.LittleEndian.Uint32(pyData[lineOff : lineOff+4]))

		// If both strings are empty, the kernel walker failed to read
		// the code object (e.g. non-compact ASCII or bad pointer). Skip
		// rather than leak a blank entry into the resolver.
		if filename == "" && funcname == "" {
			continue
		}
		frames = append(frames, events.PyFrame{
			Filename: filename,
			Function: funcname,
			Line:     int(line),
		})
	}
	return frames
}

// cstring converts a fixed-width, NUL-padded char buffer into a Go string,
// trimming at the first NUL. Returns "" when the buffer begins with NUL.
func cstring(buf []byte) string {
	n := bytes.IndexByte(buf, 0)
	if n < 0 {
		n = len(buf)
	}
	if n == 0 {
		return ""
	}
	return string(buf[:n])
}

// Close releases all eBPF resources. Safe to call multiple times (idempotent).
// Closes in reverse order: reader → links → unpin watchdog → objects.
func (t *Tracer) Close() error {
	if t.closed.Swap(true) {
		return nil // Already closed
	}

	var errs []error
	if t.reader != nil {
		if err := t.reader.Close(); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errs = append(errs, err)
		}
	}
	for _, l := range t.links {
		if err := l.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	t.links = nil
	// Unpin watchdog map before closing the object — prevents orphaned pins
	// from accumulating across SIGINT/SIGTERM exits (Bug 10).
	os.Remove(watchdogPinPath)
	if err := t.objs.Close(); err != nil {
		errs = append(errs, fmt.Errorf("closing eBPF objects: %w", err))
	}
	return errors.Join(errs...)
}

// SetSamplingRate updates the BPF sampling rate for this tracer.
// Rate 0 or 1 = emit all events. Rate N > 1 = emit 1 in N events
// (per-CPU, so actual ratio varies slightly).
//
// Must be called after Attach(). Thread-safe.
func (t *Tracer) SetSamplingRate(rate uint32) error {
	if t.objs.ConfigMap == nil {
		return fmt.Errorf("config map not initialized — call Attach first")
	}
	// Build the full 12-byte ingero_config struct (u32 alignment, no trailing pad).
	var cfg [12]byte
	if t.stackEnabled {
		cfg[0] = 1
	}
	// sampling_rate at offset 4 (little-endian uint32)
	binary.LittleEndian.PutUint32(cfg[4:8], rate)
	if err := t.objs.ConfigMap.Put(uint32(0), cfg[:]); err != nil {
		return fmt.Errorf("updating sampling rate: %w", err)
	}
	return nil
}

// LibPath returns the path to the libcudart.so being traced.
func (t *Tracer) LibPath() string {
	return t.libPath
}

// PyRuntimeMap returns the py_runtime_map loaded as part of cuda_trace.bpf.c
// (via the included bpf/python_walker.bpf.h header). Callers use this to
// push per-PID CPython runtime state for the in-kernel Python frame walker
// invoked by --py-walker=ebpf.
//
// Returns nil when the map is not present in the generated bindings — this
// happens before `make generate` is run after adding the walker header.
// The caller must nil-check and fall back to the userspace walker.
//
// The lookup is reflection-based so the cuda package compiles both before
// and after bpf2go regenerates to include py_runtime_map. Once the field
// is present in cudaTraceMaps, the reflection path resolves it at runtime.
func (t *Tracer) PyRuntimeMap() *ebpf.Map {
	return lookupMapField(&t.objs.cudaTraceMaps, "PyRuntimeMap")
}

// PyDebugStatsMap returns the per-CPU py_debug_stats counter map used to
// diagnose why the in-kernel Python walker is (or isn't) emitting frames.
// Returns nil when the map isn't present in the generated bindings.
func (t *Tracer) PyDebugStatsMap() *ebpf.Map {
	return lookupMapField(&t.objs.cudaTraceMaps, "PyDebugStats")
}

// ProbeCount returns the number of attached probes.
func (t *Tracer) ProbeCount() int {
	return len(t.links)
}

// Dropped returns the number of events dropped due to a full channel.
// This is an atomic counter — safe to call from any goroutine.
func (t *Tracer) Dropped() uint64 {
	return t.dropped.Load()
}

// ReadErrors returns the number of ring buffer read errors (transient kernel-side failures).
func (t *Tracer) ReadErrors() uint64 {
	return t.readErrors.Load()
}

// ParseErrors returns the number of malformed events that failed to parse.
func (t *Tracer) ParseErrors() uint64 {
	return t.parseErrors.Load()
}
