// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package kernellaunch

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kernelLaunchKernelLaunchEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	CgroupId    uint64
	FuncHandle  uint64
	Pid         uint32
	Tgid        uint32
	GridX       uint32
	GridY       uint32
	GridZ       uint32
	BlockX      uint32
	BlockY      uint32
	Pad0        uint32
}

// loadKernelLaunch returns the embedded CollectionSpec for kernelLaunch.
func loadKernelLaunch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KernelLaunchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kernelLaunch: %w", err)
	}

	return spec, err
}

// loadKernelLaunchObjects loads kernelLaunch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kernelLaunchObjects
//	*kernelLaunchPrograms
//	*kernelLaunchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKernelLaunchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKernelLaunch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kernelLaunchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelLaunchSpecs struct {
	kernelLaunchProgramSpecs
	kernelLaunchMapSpecs
	kernelLaunchVariableSpecs
}

// kernelLaunchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelLaunchProgramSpecs struct {
	UprobeCuLaunchKernel *ebpf.ProgramSpec `ebpf:"uprobe_cu_launch_kernel"`
}

// kernelLaunchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelLaunchMapSpecs struct {
	IngeroWatchdog     *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	KernelLaunchEvents *ebpf.MapSpec `ebpf:"kernel_launch_events"`
}

// kernelLaunchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelLaunchVariableSpecs struct {
	UnusedKernelLaunchEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_kernel_launch_event_force_btf"`
}

// kernelLaunchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKernelLaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelLaunchObjects struct {
	kernelLaunchPrograms
	kernelLaunchMaps
	kernelLaunchVariables
}

func (o *kernelLaunchObjects) Close() error {
	return _KernelLaunchClose(
		&o.kernelLaunchPrograms,
		&o.kernelLaunchMaps,
	)
}

// kernelLaunchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKernelLaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelLaunchMaps struct {
	IngeroWatchdog     *ebpf.Map `ebpf:"ingero_watchdog"`
	KernelLaunchEvents *ebpf.Map `ebpf:"kernel_launch_events"`
}

func (m *kernelLaunchMaps) Close() error {
	return _KernelLaunchClose(
		m.IngeroWatchdog,
		m.KernelLaunchEvents,
	)
}

// kernelLaunchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKernelLaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelLaunchVariables struct {
	UnusedKernelLaunchEventForceBtf *ebpf.Variable `ebpf:"_unused_kernel_launch_event_force_btf"`
}

// kernelLaunchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKernelLaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelLaunchPrograms struct {
	UprobeCuLaunchKernel *ebpf.Program `ebpf:"uprobe_cu_launch_kernel"`
}

func (p *kernelLaunchPrograms) Close() error {
	return _KernelLaunchClose(
		p.UprobeCuLaunchKernel,
	)
}

func _KernelLaunchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kernellaunch_arm64_bpfel.o
var _KernelLaunchBytes []byte
