// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package net

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netTraceIngeroNetEvent struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		TimestampNs uint64
		Pid         uint32
		Tid         uint32
		Source      uint8
		Op          uint8
		Pad         uint16
		Pad2        uint32
		CgroupId    uint64
		Comm        [16]int8
	}
	DurationNs uint64
	Fd         uint32
	Bytes      uint32
	Direction  uint8
	PadNet     [7]uint8
}

type netTraceNetEntry struct {
	_           structs.HostLayout
	TimestampNs uint64
	Fd          uint32
	Len         uint32
	Op          uint8
	Pad         [7]uint8
}

// loadNetTrace returns the embedded CollectionSpec for netTrace.
func loadNetTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netTrace: %w", err)
	}

	return spec, err
}

// loadNetTraceObjects loads netTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netTraceObjects
//	*netTracePrograms
//	*netTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netTraceSpecs struct {
	netTraceProgramSpecs
	netTraceMapSpecs
	netTraceVariableSpecs
}

// netTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netTraceProgramSpecs struct {
	HandleSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"handle_sys_enter_recvfrom"`
	HandleSysEnterSendto   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_sendto"`
	HandleSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_recvfrom"`
	HandleSysExitSendto    *ebpf.ProgramSpec `ebpf:"handle_sys_exit_sendto"`
}

// netTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netTraceMapSpecs struct {
	IngeroWatchdog *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	NetEntryMap    *ebpf.MapSpec `ebpf:"net_entry_map"`
	NetEvents      *ebpf.MapSpec `ebpf:"net_events"`
	NetTargetPids  *ebpf.MapSpec `ebpf:"net_target_pids"`
}

// netTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netTraceVariableSpecs struct {
	UnusedNetEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_net_event_force_btf"`
}

// netTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type netTraceObjects struct {
	netTracePrograms
	netTraceMaps
	netTraceVariables
}

func (o *netTraceObjects) Close() error {
	return _NetTraceClose(
		&o.netTracePrograms,
		&o.netTraceMaps,
	)
}

// netTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type netTraceMaps struct {
	IngeroWatchdog *ebpf.Map `ebpf:"ingero_watchdog"`
	NetEntryMap    *ebpf.Map `ebpf:"net_entry_map"`
	NetEvents      *ebpf.Map `ebpf:"net_events"`
	NetTargetPids  *ebpf.Map `ebpf:"net_target_pids"`
}

func (m *netTraceMaps) Close() error {
	return _NetTraceClose(
		m.IngeroWatchdog,
		m.NetEntryMap,
		m.NetEvents,
		m.NetTargetPids,
	)
}

// netTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type netTraceVariables struct {
	UnusedNetEventForceBtf *ebpf.Variable `ebpf:"_unused_net_event_force_btf"`
}

// netTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type netTracePrograms struct {
	HandleSysEnterRecvfrom *ebpf.Program `ebpf:"handle_sys_enter_recvfrom"`
	HandleSysEnterSendto   *ebpf.Program `ebpf:"handle_sys_enter_sendto"`
	HandleSysExitRecvfrom  *ebpf.Program `ebpf:"handle_sys_exit_recvfrom"`
	HandleSysExitSendto    *ebpf.Program `ebpf:"handle_sys_exit_sendto"`
}

func (p *netTracePrograms) Close() error {
	return _NetTraceClose(
		p.HandleSysEnterRecvfrom,
		p.HandleSysEnterSendto,
		p.HandleSysExitRecvfrom,
		p.HandleSysExitSendto,
	)
}

func _NetTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nettrace_bpfel.o
var _NetTraceBytes []byte
