// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package memfrag

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type memfragKprobeMemfragIoctlEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	CgroupId    uint64
	Tid         uint32
	Pid         uint32
	Cmd         uint32
	Pad0        uint32
}

// loadMemfragKprobe returns the embedded CollectionSpec for memfragKprobe.
func loadMemfragKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemfragKprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load memfragKprobe: %w", err)
	}

	return spec, err
}

// loadMemfragKprobeObjects loads memfragKprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*memfragKprobeObjects
//	*memfragKprobePrograms
//	*memfragKprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMemfragKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMemfragKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// memfragKprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memfragKprobeSpecs struct {
	memfragKprobeProgramSpecs
	memfragKprobeMapSpecs
	memfragKprobeVariableSpecs
}

// memfragKprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memfragKprobeProgramSpecs struct {
	NvidiaUnlockedIoctlEnter *ebpf.ProgramSpec `ebpf:"nvidia_unlocked_ioctl_enter"`
}

// memfragKprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memfragKprobeMapSpecs struct {
	IngeroWatchdog *ebpf.MapSpec `ebpf:"ingero_watchdog"`
	MemfragEvents  *ebpf.MapSpec `ebpf:"memfrag_events"`
}

// memfragKprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memfragKprobeVariableSpecs struct {
	UnusedMemfragIoctlEventForceBtf *ebpf.VariableSpec `ebpf:"_unused_memfrag_ioctl_event_force_btf"`
}

// memfragKprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMemfragKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type memfragKprobeObjects struct {
	memfragKprobePrograms
	memfragKprobeMaps
	memfragKprobeVariables
}

func (o *memfragKprobeObjects) Close() error {
	return _MemfragKprobeClose(
		&o.memfragKprobePrograms,
		&o.memfragKprobeMaps,
	)
}

// memfragKprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMemfragKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type memfragKprobeMaps struct {
	IngeroWatchdog *ebpf.Map `ebpf:"ingero_watchdog"`
	MemfragEvents  *ebpf.Map `ebpf:"memfrag_events"`
}

func (m *memfragKprobeMaps) Close() error {
	return _MemfragKprobeClose(
		m.IngeroWatchdog,
		m.MemfragEvents,
	)
}

// memfragKprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMemfragKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type memfragKprobeVariables struct {
	UnusedMemfragIoctlEventForceBtf *ebpf.Variable `ebpf:"_unused_memfrag_ioctl_event_force_btf"`
}

// memfragKprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMemfragKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type memfragKprobePrograms struct {
	NvidiaUnlockedIoctlEnter *ebpf.Program `ebpf:"nvidia_unlocked_ioctl_enter"`
}

func (p *memfragKprobePrograms) Close() error {
	return _MemfragKprobeClose(
		p.NvidiaUnlockedIoctlEnter,
	)
}

func _MemfragKprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memfragkprobe_x86_bpfel.o
var _MemfragKprobeBytes []byte
